version: "2"

run:
  timeout: 5m
  tests: true

linters:
  disable-all: true
  enable:
    # --- Default & Critical ---
    - errcheck
    - govet
    - staticcheck
    - unused

    # --- Error Handling & Naming ---
    - errname # Enforces "Err" prefix and "Error" suffix
    - errorlint # Enforces Go 1.13+ error wrapping (%w)
    - nilerr # Finds code that returns nil even if checks fail

    # --- Database & Logging ---
    - sqlclosecheck # Prevents connection leaks (vital for SQLite)
    - rowserrcheck # Ensures rows.Err() is checked after iteration
    - sloglint # Ensures structured logging consistency

    # --- Quality & Security ---
    - revive # General Go style
    - gosec # Security (SQL Injection, file permissions)
    - gocritic # Catches subtle bugs and performance issues
    - misspell # Fixes typos
    - nolintlint # Ensures //nolint comments are actually needed
    - testifylint # Ensures correct testify usage

linters-settings:
  errcheck:
    exclude-functions:
      - (*net/http.Response).Body.Close

  sloglint:
    kv-only: true

issues:
  exclude-dirs:
    - vendor
    - context # External repos cloned for reference
  exclude-rules:
    - path: _test\.go
      linters:
        - gosec # Security checks less critical in tests
