# https://taskfile.dev

version: "3"

vars:
  MODELS_DIR: testdata/models
  SEEDS_DIR: testdata/seeds
  STATE_FILE: .leapsql/state.db
  DATABASE: ""

tasks:
  default:
    desc: Show available tasks
    cmds:
      - task --list
    silent: true

  build:
    desc: Build the leapsql CLI
    cmds:
      - go build -o leapsql ./cmd/leapsql

  install:
    desc: Install leapsql CLI to $GOPATH/bin
    cmds:
      - go install ./cmd/leapsql

  test:
    desc: Run all tests (package summary, shows failures inline)
    cmds:
      - gotestsum --format pkgname-and-test-fails ./...

  test:pkg:
    desc: Run tests for a specific package (use PKG=./internal/cli/...)
    cmds:
      - gotestsum --format testname {{.PKG}}
    requires:
      vars: [PKG]

  test:watch:
    desc: Watch mode - rerun tests on file changes
    cmds:
      - gotestsum --watch --format pkgname-and-test-fails ./...

  test:all:
    desc: Run all tests including integration tests
    cmds:
      - gotestsum --format pkgname-and-test-fails -- -tags=integration ./...

  lint:
    desc: Run golangci-lint on all packages
    cmds:
      - golangci-lint run ./...

  lint:fix:
    desc: Run golangci-lint with auto-fix
    cmds:
      - golangci-lint run --fix ./...

  check:
    desc: Run tests and linting
    cmds:
      - task: test
      - task: lint

  generate:
    desc: Run all go generate directives (sqlc)
    cmds:
      - go generate ./...

  generate:dialect:
    desc: Generate DuckDB dialect metadata (functions, keywords, types)
    cmds:
      - go run ./scripts/gendialect -dialect=duckdb -gen=all -outdir=pkg/adapters/duckdb/dialect

  generate:all:
    desc: Run all code generation (sqlc + dialect)
    cmds:
      - task: generate
      - task: generate:dialect

  run:
    desc: Run all models
    deps: [build]
    cmds:
      - ./leapsql run -models {{.MODELS_DIR}} -seeds {{.SEEDS_DIR}} -state {{.STATE_FILE}} {{if .DATABASE}}-database {{.DATABASE}}{{end}} -v

  run:select:
    desc: Run selected models (use MODEL=staging.stg_customers)
    deps: [build]
    cmds:
      - ./leapsql run -models {{.MODELS_DIR}} -seeds {{.SEEDS_DIR}} -state {{.STATE_FILE}} {{if .DATABASE}}-database {{.DATABASE}}{{end}} -select {{.MODEL}} -v
    requires:
      vars: [MODEL]

  run:downstream:
    desc: Run selected models with downstream (use MODEL=staging.stg_customers)
    deps: [build]
    cmds:
      - ./leapsql run -models {{.MODELS_DIR}} -seeds {{.SEEDS_DIR}} -state {{.STATE_FILE}} {{if .DATABASE}}-database {{.DATABASE}}{{end}} -select {{.MODEL}} -downstream -v
    requires:
      vars: [MODEL]

  list:
    desc: List all models and dependencies
    deps: [build]
    cmds:
      - ./leapsql list -models {{.MODELS_DIR}} -seeds {{.SEEDS_DIR}} -state {{.STATE_FILE}}

  dag:
    desc: Show dependency graph
    deps: [build]
    cmds:
      - ./leapsql dag -models {{.MODELS_DIR}} -seeds {{.SEEDS_DIR}} -state {{.STATE_FILE}}

  seed:
    desc: Load seed data
    deps: [build]
    cmds:
      - ./leapsql seed -models {{.MODELS_DIR}} -seeds {{.SEEDS_DIR}} -state {{.STATE_FILE}} {{if .DATABASE}}-database {{.DATABASE}}{{end}}

  version:
    desc: Show version
    deps: [build]
    cmds:
      - ./leapsql version

  docs:build:
    desc: Generate static documentation site
    deps: [build]
    cmds:
      - ./leapsql docs build -models {{.MODELS_DIR}} -output docs-site -project "LeapSQL Project"

  docs:serve:
    desc: Build and serve documentation locally
    deps: [build]
    cmds:
      - ./leapsql docs serve -models {{.MODELS_DIR}} -port 8080 -project "LeapSQL Project"

  clean:
    desc: Clean build artifacts and state
    cmds:
      - rm -f leapsql
      - rm -rf .leapsql
      - rm -rf .leapsql-docs
      - rm -rf docs-site

  docs:dev:
    desc: Start Astro docs development server
    dir: docs
    cmds:
      - pnpm install
      - pnpm dev

  context:sqlglot:
    desc: Shallow clone sqlglot repository into context/
    cmds:
      - rm -rf context/sqlglot
      - git clone --depth 1 https://github.com/tobymao/sqlglot.git context/sqlglot

  context:dbt-core:
    desc: Shallow clone dbt-core repository into context/
    cmds:
      - rm -rf context/dbt-core
      - git clone --depth 1 https://github.com/dbt-labs/dbt-core.git context/dbt-core

  context:sqlmesh:
    desc: Shallow clone sqlmesh repository into context/
    cmds:
      - rm -rf context/sqlmesh
      - git clone --depth 1 https://github.com/TobikoData/sqlmesh.git context/sqlmesh

  context:all:
    desc: Shallow clone all context repositories
    cmds:
      - task: context:sqlglot
      - task: context:dbt-core
      - task: context:sqlmesh
