# https://taskfile.dev

version: '3'

vars:
  MODELS_DIR: testdata/models
  SEEDS_DIR: testdata/seeds
  STATE_FILE: .dbgo/state.db
  DATABASE: ""

tasks:
  default:
    desc: Show available tasks
    cmds:
      - task --list
    silent: true

  build:
    desc: Build the dbgo CLI
    cmds:
      - go build -o dbgo ./cmd/dbgo

  test:
    desc: Run all tests
    cmds:
      - go test ./...

  test:verbose:
    desc: Run all tests with verbose output
    cmds:
      - go test -v ./...

  run:
    desc: Run all models
    deps: [build]
    cmds:
      - ./dbgo run -models {{.MODELS_DIR}} -seeds {{.SEEDS_DIR}} -state {{.STATE_FILE}} {{if .DATABASE}}-database {{.DATABASE}}{{end}} -v

  run:select:
    desc: Run selected models (use MODEL=staging.stg_customers)
    deps: [build]
    cmds:
      - ./dbgo run -models {{.MODELS_DIR}} -seeds {{.SEEDS_DIR}} -state {{.STATE_FILE}} {{if .DATABASE}}-database {{.DATABASE}}{{end}} -select {{.MODEL}} -v
    requires:
      vars: [MODEL]

  run:downstream:
    desc: Run selected models with downstream (use MODEL=staging.stg_customers)
    deps: [build]
    cmds:
      - ./dbgo run -models {{.MODELS_DIR}} -seeds {{.SEEDS_DIR}} -state {{.STATE_FILE}} {{if .DATABASE}}-database {{.DATABASE}}{{end}} -select {{.MODEL}} -downstream -v
    requires:
      vars: [MODEL]

  list:
    desc: List all models and dependencies
    deps: [build]
    cmds:
      - ./dbgo list -models {{.MODELS_DIR}} -seeds {{.SEEDS_DIR}} -state {{.STATE_FILE}}

  dag:
    desc: Show dependency graph
    deps: [build]
    cmds:
      - ./dbgo dag -models {{.MODELS_DIR}} -seeds {{.SEEDS_DIR}} -state {{.STATE_FILE}}

  seed:
    desc: Load seed data
    deps: [build]
    cmds:
      - ./dbgo seed -models {{.MODELS_DIR}} -seeds {{.SEEDS_DIR}} -state {{.STATE_FILE}} {{if .DATABASE}}-database {{.DATABASE}}{{end}}

  version:
    desc: Show version
    deps: [build]
    cmds:
      - ./dbgo version

  docs:build:
    desc: Generate static documentation site
    deps: [build]
    cmds:
      - ./dbgo docs build -models {{.MODELS_DIR}} -output ./docs-site -project "DBGo Project"

  docs:serve:
    desc: Build and serve documentation locally
    deps: [build]
    cmds:
      - ./dbgo docs serve -models {{.MODELS_DIR}} -port 8080 -project "DBGo Project"

  clean:
    desc: Clean build artifacts and state
    cmds:
      - rm -f dbgo
      - rm -rf .dbgo
      - rm -rf .dbgo-docs
      - rm -rf docs-site

  context:sqlglot:
    desc: Shallow clone sqlglot repository into context/
    cmds:
      - rm -rf context/sqlglot
      - git clone --depth 1 https://github.com/tobymao/sqlglot.git context/sqlglot

  context:dbt-core:
    desc: Shallow clone dbt-core repository into context/
    cmds:
      - rm -rf context/dbt-core
      - git clone --depth 1 https://github.com/dbt-labs/dbt-core.git context/dbt-core

  context:sqlmesh:
    desc: Shallow clone sqlmesh repository into context/
    cmds:
      - rm -rf context/sqlmesh
      - git clone --depth 1 https://github.com/TobikoData/sqlmesh.git context/sqlmesh

  context:all:
    desc: Shallow clone all context repositories
    cmds:
      - task: context:sqlglot
      - task: context:dbt-core
      - task: context:sqlmesh
