# https://taskfile.dev

version: "3"

vars:
  MODELS_DIR: testdata/models
  SEEDS_DIR: testdata/seeds
  STATE_FILE: .leapsql/state.db
  DATABASE: ""

  # cssgen common parameters
  CSSGEN_SOURCE: internal/ui/resources/static/css
  CSSGEN_OUTPUT_DIR: internal/ui/cssgen
  CSSGEN_PACKAGE: cssgen
  CSSGEN_LINT_PATHS: "internal/ui/features/**/*.templ"

tasks:
  default:
    desc: Show available tasks
    cmds:
      - task --list
    silent: true

  build:
    desc: Build the leapsql CLI
    sources:
      - "**/*.go"
      - go.mod
      - go.sum
    generates:
      - leapsql
    cmds:
      - go build -o leapsql ./cmd/leapsql

  install:
    desc: Install leapsql CLI to $GOPATH/bin
    cmds:
      - go install ./cmd/leapsql

  test:
    desc: Run all tests (package summary, shows failures inline)
    cmds:
      - gotestsum --format pkgname-and-test-fails -- $(go list ./... | grep -v '/pkg/core')

  test:pkg:
    desc: Run tests for a specific package (use PKG=./internal/cli/...)
    cmds:
      - gotestsum --format testname -- {{.PKG}}
    requires:
      vars: [PKG]

  test:watch:
    desc: Watch mode - rerun tests on file changes
    cmds:
      - gotestsum --watch --format pkgname-and-test-fails -- $(go list ./... | grep -v '/pkg/core')

  test:all:
    desc: Run all tests including integration tests
    cmds:
      - gotestsum --format pkgname-and-test-fails -- -tags=integration $(go list ./... | grep -v '/pkg/core')

  lint:
    desc: Run golangci-lint on all packages
    cmds:
      - golangci-lint run ./...

  lint:fix:
    desc: Run golangci-lint with auto-fix
    cmds:
      - golangci-lint run --fix ./...

  governance:
    desc: Run all architecture governance tests (arch + cohesion + purity)
    cmds:
      - go test -tags=governance ./pkg/core/... -v

  check:
    desc: Run tests, linting, and CSS linting
    ignore_error: true
    cmds:
      - task: test
      - task: lint
      - task: css:lint

  generate:
    desc: Run all go generate directives (sqlc + cssgen)
    cmds:
      - go generate ./...
      - task: generate:css

  generate:dialect:
    desc: Generate DuckDB dialect metadata (functions, keywords, types)
    cmds:
      - go run ./scripts/gendialect -dialect=duckdb -gen=all -outdir=pkg/adapters/duckdb/dialect

  generate:databricks:
    desc: Generate Databricks dialect metadata from documentation
    cmds:
      - go run ./scripts/gendatabricks -gen=all -outdir=pkg/dialects/databricks/

  generate:snowflake:
    desc: Generate Snowflake dialect metadata from documentation
    cmds:
      - go run ./scripts/gensnowflake -gen=all -outdir=pkg/dialects/snowflake/

  docs:generate:
    desc: Generate documentation from code
    cmds:
      - go run ./scripts/gendocs -gen=all

  docs:generate:cli:
    desc: Generate CLI reference documentation
    cmds:
      - go run ./scripts/gendocs -gen=cli

  docs:generate:schema:
    desc: Generate schema documentation (frontmatter, config)
    cmds:
      - go run ./scripts/gendocs -gen=schema

  docs:generate:globals:
    desc: Generate template globals documentation
    cmds:
      - go run ./scripts/gendocs -gen=globals

  docs:check:
    desc: Verify generated docs are up-to-date
    cmds:
      - task: docs:generate
      - git diff --exit-code docs/

  generate:all:
    desc: Run all code generation (sqlc + dialect + docs)
    cmds:
      - task: generate
      - task: generate:dialect
      - task: generate:databricks
      - task: generate:snowflake
      - task: docs:generate

  run:
    desc: Run all models
    deps: [build]
    cmds:
      - ./leapsql run -models {{.MODELS_DIR}} -seeds {{.SEEDS_DIR}} -state {{.STATE_FILE}} {{if .DATABASE}}-database {{.DATABASE}}{{end}} -v

  run:select:
    desc: Run selected models (use MODEL=staging.stg_customers)
    deps: [build]
    cmds:
      - ./leapsql run -models {{.MODELS_DIR}} -seeds {{.SEEDS_DIR}} -state {{.STATE_FILE}} {{if .DATABASE}}-database {{.DATABASE}}{{end}} -select {{.MODEL}} -v
    requires:
      vars: [MODEL]

  run:downstream:
    desc: Run selected models with downstream (use MODEL=staging.stg_customers)
    deps: [build]
    cmds:
      - ./leapsql run -models {{.MODELS_DIR}} -seeds {{.SEEDS_DIR}} -state {{.STATE_FILE}} {{if .DATABASE}}-database {{.DATABASE}}{{end}} -select {{.MODEL}} -downstream -v
    requires:
      vars: [MODEL]

  list:
    desc: List all models and dependencies
    deps: [build]
    cmds:
      - ./leapsql list -models {{.MODELS_DIR}} -seeds {{.SEEDS_DIR}} -state {{.STATE_FILE}}

  dag:
    desc: Show dependency graph
    deps: [build]
    cmds:
      - ./leapsql dag -models {{.MODELS_DIR}} -seeds {{.SEEDS_DIR}} -state {{.STATE_FILE}}

  seed:
    desc: Load seed data
    deps: [build]
    cmds:
      - ./leapsql seed -models {{.MODELS_DIR}} -seeds {{.SEEDS_DIR}} -state {{.STATE_FILE}} {{if .DATABASE}}-database {{.DATABASE}}{{end}}

  version:
    desc: Show version
    deps: [build]
    cmds:
      - ./leapsql version

  clean:
    desc: Clean build artifacts and state
    cmds:
      - rm -f leapsql
      - rm -rf .leapsql
      - rm -rf .leapsql-docs
      - rm -rf catalog-site

  # Model Catalog (leapsql docs command - generates HTML from SQL models)
  catalog:build:
    desc: Generate static model catalog site (use THEME=vercel|claude|corporate)
    deps: [build]
    cmds:
      - ./leapsql docs build --models {{.MODELS_DIR}} --output catalog-site --project "LeapSQL Project" {{if .THEME}}--theme {{.THEME}}{{end}}

  catalog:serve:
    desc: Build and serve model catalog locally (use THEME=vercel|claude|corporate)
    deps: [build]
    cmds:
      - ./leapsql docs serve --models {{.MODELS_DIR}} --port 8080 --project "LeapSQL Project" {{if .THEME}}--theme {{.THEME}}{{end}}

  catalog:dev:
    desc: Start model catalog dev server with live reload (use THEME=vercel|claude|corporate)
    deps: [build]
    cmds:
      - ./leapsql docs dev --models {{.MODELS_DIR}} --port 8080 --project "LeapSQL Project" {{if .THEME}}--theme {{.THEME}}{{end}}

  # Project Documentation (VitePress in /docs folder)
  docs:dev:
    desc: Start VitePress docs development server
    dir: docs
    cmds:
      - pnpm install
      - pnpm dev

  context:sqlglot:
    desc: Shallow clone sqlglot repository into context/
    cmds:
      - rm -rf context/sqlglot
      - git clone --depth 1 https://github.com/tobymao/sqlglot.git context/sqlglot

  context:dbt-core:
    desc: Shallow clone dbt-core repository into context/
    cmds:
      - rm -rf context/dbt-core
      - git clone --depth 1 https://github.com/dbt-labs/dbt-core.git context/dbt-core

  context:sqlmesh:
    desc: Shallow clone sqlmesh repository into context/
    cmds:
      - rm -rf context/sqlmesh
      - git clone --depth 1 https://github.com/TobikoData/sqlmesh.git context/sqlmesh

  context:datastar:
    desc: Sync Datastar documentation into context/
    cmds:
      - go run ./scripts/syncdatastardocs

  context:all:
    desc: Shallow clone all context repositories
    cmds:
      - task: context:sqlglot
      - task: context:dbt-core
      - task: context:sqlmesh
      - task: context:datastar

  # UI Development
  ui:
    desc: Start UI development server
    deps: [build]
    cmds:
      - ./leapsql ui --models-dir {{.MODELS_DIR}}

  ui:dev:
    desc: Start UI dev server with hot reload (requires templ watch)
    cmds:
      - go run -tags dev ./cmd/leapsql ui --models-dir {{.MODELS_DIR}}

  templ:
    desc: Generate templ files
    cmds:
      - templ generate ./internal/ui/...

  templ:watch:
    desc: Watch templ files and regenerate on change
    cmds:
      - templ generate --watch ./internal/ui/...

  # UI Component Build
  ui:build:js:
    desc: Build UI JavaScript components
    dir: internal/ui/web
    cmds:
      - pnpm install
      - pnpm build
      - mkdir -p ../resources/static/js
      - cp static/js/*.js ../resources/static/js/

  ui:build:js:dev:
    desc: Build UI JavaScript components (dev mode with sourcemaps)
    dir: internal/ui/web
    cmds:
      - pnpm install
      - pnpm build:dev
      - mkdir -p ../resources/static/js
      - cp static/js/*.js ../resources/static/js/

  generate:css:
    desc: Generate type-safe CSS constants from CSS files
    sources:
      - internal/ui/resources/static/css/**/*.css
    generates:
      - internal/ui/cssgen/styles*.gen.go
    cmds:
      - cssgen -source {{.CSSGEN_SOURCE}} -output-dir {{.CSSGEN_OUTPUT_DIR}} -package {{.CSSGEN_PACKAGE}} -include "**/*.css"

  css:lint:
    desc: Lint CSS usage (golangci-lint style - issues only)
    cmds:
      - cssgen -lint-only -output-dir {{.CSSGEN_OUTPUT_DIR}} -lint-paths "{{.CSSGEN_LINT_PATHS}}"
