# https://taskfile.dev

version: "3"

vars:
  MODELS_DIR: testdata/models
  SEEDS_DIR: testdata/seeds
  STATE_FILE: .leapsql/state.db
  DATABASE: ""

tasks:
  default:
    desc: Show available tasks
    cmds:
      - task --list
    silent: true

  build:
    desc: Build the leapsql CLI
    cmds:
      - go build -tags=sqlite_fts5 -o leapsql ./cmd/leapsql

  install:
    desc: Install leapsql CLI to $GOPATH/bin
    cmds:
      - go install -tags=sqlite_fts5 ./cmd/leapsql

  test:
    desc: Run all tests (package summary, shows failures inline)
    cmds:
      - gotestsum --format pkgname-and-test-fails -- -tags=sqlite_fts5 $(go list ./... | grep -v '/pkg/core')

  test:pkg:
    desc: Run tests for a specific package (use PKG=./internal/cli/...)
    cmds:
      - gotestsum --format testname -- -tags=sqlite_fts5 {{.PKG}}
    requires:
      vars: [PKG]

  test:watch:
    desc: Watch mode - rerun tests on file changes
    cmds:
      - gotestsum --watch --format pkgname-and-test-fails -- -tags=sqlite_fts5 $(go list ./... | grep -v '/pkg/core')

  test:all:
    desc: Run all tests including integration tests
    cmds:
      - gotestsum --format pkgname-and-test-fails -- -tags=integration,sqlite_fts5 $(go list ./... | grep -v '/pkg/core')

  lint:
    desc: Run golangci-lint on all packages
    cmds:
      - golangci-lint run ./...

  lint:fix:
    desc: Run golangci-lint with auto-fix
    cmds:
      - golangci-lint run --fix ./...

  governance:
    desc: Run all architecture governance tests (arch + cohesion + purity)
    cmds:
      - go test -tags=governance ./pkg/core/... -v

  check:
    desc: Run tests and linting
    cmds:
      - task: test
      - task: lint

  generate:
    desc: Run all go generate directives (sqlc)
    cmds:
      - go generate ./...

  generate:dialect:
    desc: Generate DuckDB dialect metadata (functions, keywords, types)
    cmds:
      - go run ./scripts/gendialect -dialect=duckdb -gen=all -outdir=pkg/adapters/duckdb/dialect

  docs:generate:
    desc: Generate documentation from code
    cmds:
      - go run ./scripts/gendocs -gen=all

  docs:generate:cli:
    desc: Generate CLI reference documentation
    cmds:
      - go run ./scripts/gendocs -gen=cli

  docs:generate:schema:
    desc: Generate schema documentation (frontmatter, config)
    cmds:
      - go run ./scripts/gendocs -gen=schema

  docs:generate:globals:
    desc: Generate template globals documentation
    cmds:
      - go run ./scripts/gendocs -gen=globals

  docs:check:
    desc: Verify generated docs are up-to-date
    cmds:
      - task: docs:generate
      - git diff --exit-code docs/

  generate:all:
    desc: Run all code generation (sqlc + dialect + docs)
    cmds:
      - task: generate
      - task: generate:dialect
      - task: docs:generate

  run:
    desc: Run all models
    deps: [build]
    cmds:
      - ./leapsql run -models {{.MODELS_DIR}} -seeds {{.SEEDS_DIR}} -state {{.STATE_FILE}} {{if .DATABASE}}-database {{.DATABASE}}{{end}} -v

  run:select:
    desc: Run selected models (use MODEL=staging.stg_customers)
    deps: [build]
    cmds:
      - ./leapsql run -models {{.MODELS_DIR}} -seeds {{.SEEDS_DIR}} -state {{.STATE_FILE}} {{if .DATABASE}}-database {{.DATABASE}}{{end}} -select {{.MODEL}} -v
    requires:
      vars: [MODEL]

  run:downstream:
    desc: Run selected models with downstream (use MODEL=staging.stg_customers)
    deps: [build]
    cmds:
      - ./leapsql run -models {{.MODELS_DIR}} -seeds {{.SEEDS_DIR}} -state {{.STATE_FILE}} {{if .DATABASE}}-database {{.DATABASE}}{{end}} -select {{.MODEL}} -downstream -v
    requires:
      vars: [MODEL]

  list:
    desc: List all models and dependencies
    deps: [build]
    cmds:
      - ./leapsql list -models {{.MODELS_DIR}} -seeds {{.SEEDS_DIR}} -state {{.STATE_FILE}}

  dag:
    desc: Show dependency graph
    deps: [build]
    cmds:
      - ./leapsql dag -models {{.MODELS_DIR}} -seeds {{.SEEDS_DIR}} -state {{.STATE_FILE}}

  seed:
    desc: Load seed data
    deps: [build]
    cmds:
      - ./leapsql seed -models {{.MODELS_DIR}} -seeds {{.SEEDS_DIR}} -state {{.STATE_FILE}} {{if .DATABASE}}-database {{.DATABASE}}{{end}}

  version:
    desc: Show version
    deps: [build]
    cmds:
      - ./leapsql version

  clean:
    desc: Clean build artifacts and state
    cmds:
      - rm -f leapsql
      - rm -rf .leapsql
      - rm -rf .leapsql-docs
      - rm -rf catalog-site

  # Model Catalog (leapsql docs command - generates HTML from SQL models)
  catalog:build:
    desc: Generate static model catalog site (use THEME=vercel|claude|corporate)
    deps: [build]
    cmds:
      - ./leapsql docs build --models {{.MODELS_DIR}} --output catalog-site --project "LeapSQL Project" {{if .THEME}}--theme {{.THEME}}{{end}}

  catalog:serve:
    desc: Build and serve model catalog locally (use THEME=vercel|claude|corporate)
    deps: [build]
    cmds:
      - ./leapsql docs serve --models {{.MODELS_DIR}} --port 8080 --project "LeapSQL Project" {{if .THEME}}--theme {{.THEME}}{{end}}

  catalog:dev:
    desc: Start model catalog dev server with live reload (use THEME=vercel|claude|corporate)
    deps: [build]
    cmds:
      - ./leapsql docs dev --models {{.MODELS_DIR}} --port 8080 --project "LeapSQL Project" {{if .THEME}}--theme {{.THEME}}{{end}}

  # Project Documentation (VitePress in /docs folder)
  docs:dev:
    desc: Start VitePress docs development server
    dir: docs
    cmds:
      - pnpm install
      - pnpm dev

  context:sqlglot:
    desc: Shallow clone sqlglot repository into context/
    cmds:
      - rm -rf context/sqlglot
      - git clone --depth 1 https://github.com/tobymao/sqlglot.git context/sqlglot

  context:dbt-core:
    desc: Shallow clone dbt-core repository into context/
    cmds:
      - rm -rf context/dbt-core
      - git clone --depth 1 https://github.com/dbt-labs/dbt-core.git context/dbt-core

  context:sqlmesh:
    desc: Shallow clone sqlmesh repository into context/
    cmds:
      - rm -rf context/sqlmesh
      - git clone --depth 1 https://github.com/TobikoData/sqlmesh.git context/sqlmesh

  context:all:
    desc: Shallow clone all context repositories
    cmds:
      - task: context:sqlglot
      - task: context:dbt-core
      - task: context:sqlmesh
