package commands

import (
	"fmt"
	"os"

	"github.com/spf13/cobra"
)

// NewInitCommand creates the init command.
func NewInitCommand() *cobra.Command {
	var force bool

	cmd := &cobra.Command{
		Use:   "init",
		Short: "Initialize a new LeapSQL project",
		Long: `Initialize a new LeapSQL project with default directory structure and configuration.

This creates:
  - models/ directory for SQL models
  - seeds/ directory for seed data CSV files
  - macros/ directory for Starlark macros
  - leapsql.yaml configuration file`,
		Example: `  # Initialize in current directory
  leapsql init

  # Force overwrite existing config
  leapsql init --force`,
		RunE: func(cmd *cobra.Command, args []string) error {
			return runInit(force)
		},
	}

	cmd.Flags().BoolVar(&force, "force", false, "Overwrite existing configuration")

	return cmd
}

func runInit(force bool) error {
	// Check if config already exists
	if _, err := os.Stat("leapsql.yaml"); err == nil && !force {
		return fmt.Errorf("leapsql.yaml already exists. Use --force to overwrite")
	}

	// Create directories
	dirs := []string{"models", "seeds", "macros", "models/staging", "models/marts"}
	for _, dir := range dirs {
		if err := os.MkdirAll(dir, 0755); err != nil {
			return fmt.Errorf("failed to create %s directory: %w", dir, err)
		}
		fmt.Printf("Created %s/\n", dir)
	}

	// Create config file
	configContent := `# LeapSQL Configuration
# Generated by: leapsql init

# Directory paths (relative to this config file)
models_dir: models
seeds_dir: seeds
macros_dir: macros

# Database configuration
database: ""  # Empty string for in-memory DuckDB

# State tracking
state_path: .leapsql/state.db

# Default environment
environment: dev

# Output settings
verbose: false
output: text  # text, json, or table

# Environment-specific overrides
environments:
  dev:
    database: dev.duckdb
  staging:
    database: staging.duckdb
  prod:
    database: /data/warehouse/prod.duckdb
`

	if err := os.WriteFile("leapsql.yaml", []byte(configContent), 0644); err != nil {
		return fmt.Errorf("failed to create leapsql.yaml: %w", err)
	}
	fmt.Println("Created leapsql.yaml")

	// Create example model
	exampleModel := `---
materialized: table
---
-- Example staging model
SELECT 
    1 as id,
    'example' as name,
    CURRENT_TIMESTAMP as created_at
`
	modelPath := "models/staging/stg_example.sql"
	if _, err := os.Stat(modelPath); os.IsNotExist(err) {
		if err := os.WriteFile(modelPath, []byte(exampleModel), 0644); err != nil {
			return fmt.Errorf("failed to create example model: %w", err)
		}
		fmt.Println("Created models/staging/stg_example.sql")
	}

	// Create .gitignore for LeapSQL artifacts
	gitignore := `# LeapSQL artifacts
.leapsql/
*.duckdb
*.duckdb.wal
.leapsql-docs/
docs-site/
`
	gitignorePath := ".leapsql.gitignore"
	if _, err := os.Stat(gitignorePath); os.IsNotExist(err) {
		if err := os.WriteFile(gitignorePath, []byte(gitignore), 0644); err != nil {
			fmt.Printf("Warning: failed to create .leapsql.gitignore: %v\n", err)
		} else {
			fmt.Println("Created .leapsql.gitignore (add to your .gitignore)")
		}
	}

	fmt.Println()
	fmt.Println("LeapSQL project initialized successfully!")
	fmt.Println()
	fmt.Println("Next steps:")
	fmt.Println("  1. Add your seed data to seeds/")
	fmt.Println("  2. Create SQL models in models/")
	fmt.Println("  3. Run 'leapsql run' to execute models")
	fmt.Println("  4. Run 'leapsql list' to see all models")

	return nil
}
