// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: dependencies.sql

package sqlcgen

import (
	"context"
)

const deleteDependenciesByModelID = `-- name: DeleteDependenciesByModelID :exec
DELETE FROM dependencies WHERE model_id = ?
`

func (q *Queries) DeleteDependenciesByModelID(ctx context.Context, modelID string) error {
	_, err := q.db.ExecContext(ctx, deleteDependenciesByModelID, modelID)
	return err
}

const deleteDependenciesByModelOrParent = `-- name: DeleteDependenciesByModelOrParent :exec
DELETE FROM dependencies
WHERE model_id IN (SELECT m.id FROM models m WHERE m.file_path = ?)
   OR parent_id IN (SELECT m2.id FROM models m2 WHERE m2.file_path = ?)
`

type DeleteDependenciesByModelOrParentParams struct {
	FilePath   *string `json:"file_path"`
	FilePath_2 *string `json:"file_path_2"`
}

func (q *Queries) DeleteDependenciesByModelOrParent(ctx context.Context, arg DeleteDependenciesByModelOrParentParams) error {
	_, err := q.db.ExecContext(ctx, deleteDependenciesByModelOrParent, arg.FilePath, arg.FilePath_2)
	return err
}

const getDependencies = `-- name: GetDependencies :many
SELECT parent_id FROM dependencies WHERE model_id = ?
`

func (q *Queries) GetDependencies(ctx context.Context, modelID string) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, getDependencies, modelID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var parent_id string
		if err := rows.Scan(&parent_id); err != nil {
			return nil, err
		}
		items = append(items, parent_id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getDependents = `-- name: GetDependents :many
SELECT model_id FROM dependencies WHERE parent_id = ?
`

func (q *Queries) GetDependents(ctx context.Context, parentID string) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, getDependents, parentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var model_id string
		if err := rows.Scan(&model_id); err != nil {
			return nil, err
		}
		items = append(items, model_id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertDependency = `-- name: InsertDependency :exec
INSERT INTO dependencies (model_id, parent_id) VALUES (?, ?)
`

type InsertDependencyParams struct {
	ModelID  string `json:"model_id"`
	ParentID string `json:"parent_id"`
}

func (q *Queries) InsertDependency(ctx context.Context, arg InsertDependencyParams) error {
	_, err := q.db.ExecContext(ctx, insertDependency, arg.ModelID, arg.ParentID)
	return err
}
