// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: environments.sql

package sqlcgen

import (
	"context"
	"time"
)

const createEnvironment = `-- name: CreateEnvironment :one
INSERT INTO environments (name, created_at, updated_at)
VALUES (?, ?, ?)
RETURNING name, commit_ref, created_at, updated_at
`

type CreateEnvironmentParams struct {
	Name      string    `json:"name"`
	CreatedAt time.Time `json:"created_at"`
	UpdatedAt time.Time `json:"updated_at"`
}

func (q *Queries) CreateEnvironment(ctx context.Context, arg CreateEnvironmentParams) (Environment, error) {
	row := q.db.QueryRowContext(ctx, createEnvironment, arg.Name, arg.CreatedAt, arg.UpdatedAt)
	var i Environment
	err := row.Scan(
		&i.Name,
		&i.CommitRef,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getEnvironment = `-- name: GetEnvironment :one
SELECT name, commit_ref, created_at, updated_at
FROM environments
WHERE name = ?
`

func (q *Queries) GetEnvironment(ctx context.Context, name string) (Environment, error) {
	row := q.db.QueryRowContext(ctx, getEnvironment, name)
	var i Environment
	err := row.Scan(
		&i.Name,
		&i.CommitRef,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateEnvironmentRef = `-- name: UpdateEnvironmentRef :exec
UPDATE environments
SET commit_ref = ?, updated_at = ?
WHERE name = ?
`

type UpdateEnvironmentRefParams struct {
	CommitRef *string   `json:"commit_ref"`
	UpdatedAt time.Time `json:"updated_at"`
	Name      string    `json:"name"`
}

func (q *Queries) UpdateEnvironmentRef(ctx context.Context, arg UpdateEnvironmentRefParams) error {
	_, err := q.db.ExecContext(ctx, updateEnvironmentRef, arg.CommitRef, arg.UpdatedAt, arg.Name)
	return err
}
