// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: model_runs.sql

package sqlcgen

import (
	"context"
	"time"
)

const getLatestModelRun = `-- name: GetLatestModelRun :one
SELECT id, run_id, model_id, status, rows_affected, started_at, completed_at, error, render_ms, execution_ms
FROM model_runs
WHERE model_id = ?
ORDER BY started_at DESC
LIMIT 1
`

func (q *Queries) GetLatestModelRun(ctx context.Context, modelID string) (ModelRun, error) {
	row := q.db.QueryRowContext(ctx, getLatestModelRun, modelID)
	var i ModelRun
	err := row.Scan(
		&i.ID,
		&i.RunID,
		&i.ModelID,
		&i.Status,
		&i.RowsAffected,
		&i.StartedAt,
		&i.CompletedAt,
		&i.Error,
		&i.RenderMs,
		&i.ExecutionMs,
	)
	return i, err
}

const getModelRunStartedAt = `-- name: GetModelRunStartedAt :one
SELECT started_at FROM model_runs WHERE id = ?
`

func (q *Queries) GetModelRunStartedAt(ctx context.Context, id string) (time.Time, error) {
	row := q.db.QueryRowContext(ctx, getModelRunStartedAt, id)
	var started_at time.Time
	err := row.Scan(&started_at)
	return started_at, err
}

const getModelRunsForRun = `-- name: GetModelRunsForRun :many
SELECT id, run_id, model_id, status, rows_affected, started_at, completed_at, error, render_ms, execution_ms
FROM model_runs
WHERE run_id = ?
ORDER BY started_at
`

func (q *Queries) GetModelRunsForRun(ctx context.Context, runID string) ([]ModelRun, error) {
	rows, err := q.db.QueryContext(ctx, getModelRunsForRun, runID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ModelRun{}
	for rows.Next() {
		var i ModelRun
		if err := rows.Scan(
			&i.ID,
			&i.RunID,
			&i.ModelID,
			&i.Status,
			&i.RowsAffected,
			&i.StartedAt,
			&i.CompletedAt,
			&i.Error,
			&i.RenderMs,
			&i.ExecutionMs,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const recordModelRun = `-- name: RecordModelRun :exec
INSERT INTO model_runs (id, run_id, model_id, status, rows_affected, started_at, error, render_ms, execution_ms)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)
`

type RecordModelRunParams struct {
	ID           string    `json:"id"`
	RunID        string    `json:"run_id"`
	ModelID      string    `json:"model_id"`
	Status       string    `json:"status"`
	RowsAffected *int64    `json:"rows_affected"`
	StartedAt    time.Time `json:"started_at"`
	Error        *string   `json:"error"`
	RenderMs     *int64    `json:"render_ms"`
	ExecutionMs  *int64    `json:"execution_ms"`
}

func (q *Queries) RecordModelRun(ctx context.Context, arg RecordModelRunParams) error {
	_, err := q.db.ExecContext(ctx, recordModelRun,
		arg.ID,
		arg.RunID,
		arg.ModelID,
		arg.Status,
		arg.RowsAffected,
		arg.StartedAt,
		arg.Error,
		arg.RenderMs,
		arg.ExecutionMs,
	)
	return err
}

const updateModelRun = `-- name: UpdateModelRun :exec
UPDATE model_runs
SET status = ?, rows_affected = ?, completed_at = ?, error = ?, render_ms = ?, execution_ms = ?
WHERE id = ?
`

type UpdateModelRunParams struct {
	Status       string     `json:"status"`
	RowsAffected *int64     `json:"rows_affected"`
	CompletedAt  *time.Time `json:"completed_at"`
	Error        *string    `json:"error"`
	RenderMs     *int64     `json:"render_ms"`
	ExecutionMs  *int64     `json:"execution_ms"`
	ID           string     `json:"id"`
}

func (q *Queries) UpdateModelRun(ctx context.Context, arg UpdateModelRunParams) error {
	_, err := q.db.ExecContext(ctx, updateModelRun,
		arg.Status,
		arg.RowsAffected,
		arg.CompletedAt,
		arg.Error,
		arg.RenderMs,
		arg.ExecutionMs,
		arg.ID,
	)
	return err
}
