// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlcgen

import (
	"time"
)

type ColumnLineage struct {
	ModelPath    string `json:"model_path"`
	ColumnName   string `json:"column_name"`
	SourceTable  string `json:"source_table"`
	SourceColumn string `json:"source_column"`
}

type ColumnSnapshot struct {
	ID          int64      `json:"id"`
	ModelPath   string     `json:"model_path"`
	SourceTable string     `json:"source_table"`
	ColumnName  string     `json:"column_name"`
	ColumnIndex int64      `json:"column_index"`
	SnapshotAt  *time.Time `json:"snapshot_at"`
	RunID       string     `json:"run_id"`
}

type Dependency struct {
	ModelID  string `json:"model_id"`
	ParentID string `json:"parent_id"`
}

type Environment struct {
	Name      string    `json:"name"`
	CommitRef *string   `json:"commit_ref"`
	CreatedAt time.Time `json:"created_at"`
	UpdatedAt time.Time `json:"updated_at"`
}

type FileHash struct {
	FilePath    string     `json:"file_path"`
	ContentHash string     `json:"content_hash"`
	FileType    string     `json:"file_type"`
	UpdatedAt   *time.Time `json:"updated_at"`
}

type MacroFunction struct {
	Namespace string  `json:"namespace"`
	Name      string  `json:"name"`
	Args      string  `json:"args"`
	Docstring *string `json:"docstring"`
	Line      *int64  `json:"line"`
}

type MacroNamespace struct {
	Name      string     `json:"name"`
	FilePath  string     `json:"file_path"`
	Package   *string    `json:"package"`
	UpdatedAt *time.Time `json:"updated_at"`
}

type Model struct {
	ID           string    `json:"id"`
	Path         string    `json:"path"`
	Name         string    `json:"name"`
	Materialized string    `json:"materialized"`
	UniqueKey    *string   `json:"unique_key"`
	ContentHash  string    `json:"content_hash"`
	FilePath     *string   `json:"file_path"`
	Owner        *string   `json:"owner"`
	SchemaName   *string   `json:"schema_name"`
	Tags         *string   `json:"tags"`
	Tests        *string   `json:"tests"`
	Meta         *string   `json:"meta"`
	CreatedAt    time.Time `json:"created_at"`
	UpdatedAt    time.Time `json:"updated_at"`
}

type ModelColumn struct {
	ModelPath     string  `json:"model_path"`
	ColumnName    string  `json:"column_name"`
	ColumnIndex   int64   `json:"column_index"`
	TransformType *string `json:"transform_type"`
	FunctionName  *string `json:"function_name"`
}

type ModelRun struct {
	ID           string     `json:"id"`
	RunID        string     `json:"run_id"`
	ModelID      string     `json:"model_id"`
	Status       string     `json:"status"`
	RowsAffected *int64     `json:"rows_affected"`
	StartedAt    time.Time  `json:"started_at"`
	CompletedAt  *time.Time `json:"completed_at"`
	Error        *string    `json:"error"`
	ExecutionMs  *int64     `json:"execution_ms"`
}

type Run struct {
	ID          string     `json:"id"`
	Environment string     `json:"environment"`
	Status      string     `json:"status"`
	StartedAt   time.Time  `json:"started_at"`
	CompletedAt *time.Time `json:"completed_at"`
	Error       *string    `json:"error"`
}
