// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: project_meta.sql

package sqlcgen

import (
	"context"
)

const deleteProjectMeta = `-- name: DeleteProjectMeta :exec
DELETE FROM project_meta WHERE key = ?
`

func (q *Queries) DeleteProjectMeta(ctx context.Context, key string) error {
	_, err := q.db.ExecContext(ctx, deleteProjectMeta, key)
	return err
}

const getProjectMeta = `-- name: GetProjectMeta :one

SELECT value FROM project_meta WHERE key = ?
`

// Project metadata queries
func (q *Queries) GetProjectMeta(ctx context.Context, key string) (string, error) {
	row := q.db.QueryRowContext(ctx, getProjectMeta, key)
	var value string
	err := row.Scan(&value)
	return value, err
}

const listProjectMeta = `-- name: ListProjectMeta :many
SELECT key, value FROM project_meta ORDER BY key
`

func (q *Queries) ListProjectMeta(ctx context.Context) ([]ProjectMetum, error) {
	rows, err := q.db.QueryContext(ctx, listProjectMeta)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ProjectMetum{}
	for rows.Next() {
		var i ProjectMetum
		if err := rows.Scan(&i.Key, &i.Value); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setProjectMeta = `-- name: SetProjectMeta :exec
INSERT OR REPLACE INTO project_meta (key, value) VALUES (?, ?)
`

type SetProjectMetaParams struct {
	Key   string `json:"key"`
	Value string `json:"value"`
}

func (q *Queries) SetProjectMeta(ctx context.Context, arg SetProjectMetaParams) error {
	_, err := q.db.ExecContext(ctx, setProjectMeta, arg.Key, arg.Value)
	return err
}
