// Code generated by scripts/gensnowflake. DO NOT EDIT.
// Source: https://docs.snowflake.com/en/sql-reference/reserved-keywords
// Generated: 2026-01-05

package snowflake

// snowflakeCompletionKeywords contains all keywords for LSP completions.
var snowflakeCompletionKeywords = []string{
	"ACCOUNT", "ALL", "ALTER", "AND", "ANY",
	"AS", "BETWEEN", "BY", "CASE", "CAST",
	"CHECK", "COLUMN", "CONNECT", "CONNECTION", "CONSTRAINT",
	"CREATE", "CROSS", "CURRENT", "CURRENT_DATE", "CURRENT_TIME",
	"CURRENT_TIMESTAMP", "CURRENT_USER", "DATABASE", "DELETE", "DISTINCT",
	"DROP", "ELSE", "EXISTS", "FALSE", "FOLLOWING",
	"FOR", "FROM", "FULL", "GRANT", "GROUP",
	"GSCLUSTER", "HAVING", "ILIKE", "IN", "INCREMENT",
	"INNER", "INSERT", "INTERSECT", "INTO", "IS",
	"ISSUE", "JOIN", "LATERAL", "LEFT", "LIKE",
	"LOCALTIME", "LOCALTIMESTAMP", "MINUS", "NATURAL", "NOT",
	"NULL", "OF", "ON", "OR", "ORDER",
	"ORGANIZATION", "QUALIFY", "REGEXP", "REVOKE", "RIGHT",
	"RLIKE", "ROW", "ROWS", "SAMPLE", "SCHEMA",
	"SELECT", "SET", "SOME", "START", "TABLE",
	"TABLESAMPLE", "THEN", "TO", "TRIGGER", "TRUE",
	"TRY_CAST", "UNION", "UNIQUE", "UPDATE", "USING",
	"VALUES", "VIEW", "WHEN", "WHENEVER", "WHERE",
	"WINDOW", "WITH",
}

// snowflakeReservedWords contains words that need quoting when used as identifiers.
var snowflakeReservedWords = []string{
	"ACCOUNT", "ALL", "ALTER", "AND", "ANY",
	"AS", "BETWEEN", "BY", "CASE", "CAST",
	"CHECK", "COLUMN", "CONNECT", "CONNECTION", "CONSTRAINT",
	"CREATE", "CROSS", "CURRENT", "CURRENT_DATE", "CURRENT_TIME",
	"CURRENT_TIMESTAMP", "CURRENT_USER", "DATABASE", "DELETE", "DISTINCT",
	"DROP", "ELSE", "EXISTS", "FALSE", "FOLLOWING",
	"FOR", "FROM", "FULL", "GRANT", "GROUP",
	"GSCLUSTER", "HAVING", "ILIKE", "IN", "INCREMENT",
	"INNER", "INSERT", "INTERSECT", "INTO", "IS",
	"ISSUE", "JOIN", "LATERAL", "LEFT", "LIKE",
	"LOCALTIME", "LOCALTIMESTAMP", "MINUS", "NATURAL", "NOT",
	"NULL", "OF", "ON", "OR", "ORDER",
	"ORGANIZATION", "QUALIFY", "REGEXP", "REVOKE", "RIGHT",
	"RLIKE", "ROW", "ROWS", "SAMPLE", "SCHEMA",
	"SELECT", "SET", "SOME", "START", "TABLE",
	"TABLESAMPLE", "THEN", "TO", "TRIGGER", "TRUE",
	"TRY_CAST", "UNION", "UNIQUE", "UPDATE", "USING",
	"VALUES", "VIEW", "WHEN", "WHENEVER", "WHERE",
	"WINDOW", "WITH",
}
