// Code generated by cssgen. DO NOT EDIT.
//
// Component: Macros
// Generated: 2026-02-06 10:18:37

package cssgen

// Macros component styles
//
// For the full CSS class registry, see styles.gen.go

// **Layout:**
// - align-items: `center`
// - display: `flex`
// - gap: `var(--ui-space-sm)` 🎨
// - margin-bottom: `var(--ui-space-sm)` 🎨
// **Typography:**
// - font-size: `var(--ui-type-size-sm)` 🎨
const MacroBreadcrumb = "macro-breadcrumb"

// **Base:** .macro-breadcrumb
// **Context:** Use with .macro-breadcrumb for proper styling
// **Overrides:** 2 properties (color, text-decoration)
//
// **Visual:**
// - color: `var(--ui-color-surface-variant-on)` 🎨
// **Typography:**
// - text-decoration: `none`
//
// **Interactions:**
// - `:hover`: Changes color to `var(--ui-color-surface-on)`
const MacroBreadcrumbItem = "macro-breadcrumb__item"

// **Base:** .macro-breadcrumb__item
// **Context:** Use with .macro-breadcrumb__item for proper styling
// **Overrides:** 2 properties (color, font-weight)
//
// **Visual:**
// - color: `var(--ui-color-surface-on)` 🎨
// **Typography:**
// - font-weight: `var(--ui-weight-medium)` 🎨
const MacroBreadcrumbItemCurrent = "macro-breadcrumb__item--current"

// **Base:** .macro-breadcrumb
// **Context:** Use with .macro-breadcrumb for proper styling
// **Overrides:** 1 properties (color)
//
// **Visual:**
// - color: `var(--ui-color-surface-variant-on)` 🎨
const MacroBreadcrumbSeparator = "macro-breadcrumb__separator"

// **Layout:**
// - max-width: `800px`
const MacroDetail = "macro-detail"

// **Base:** .macro-detail
// **Context:** Use with .macro-detail for proper styling
// **Overrides:** 12 properties (background, border-bottom, border-collapse, border-radius, color, font-family, font-size, font-weight, padding, text-align, text-transform, width)
//
// **Visual:**
// - background: `var(--ui-color-surface-container-high)` 🎨
// - border-bottom: `var(--ui-border-sm) solid var(--ui-color-outline)` 🎨
// - border-collapse: `collapse`
// - border-radius: `var(--ui-radius-sm)` 🎨
// - color: `var(--ui-color-surface-variant-on)` 🎨
// **Layout:**
// - padding: `2px 6px`
// - width: `100%`
// **Typography:**
// - font-family: `var(--ui-font-code)` 🎨
// - font-size: `var(--ui-type-size-xs)` 🎨
// - font-weight: `var(--ui-weight-medium)` 🎨
// - text-align: `left`
// - text-transform: `uppercase`
const MacroDetailArgs = "macro-detail__args"

// **Base:** .macro-detail
// **Context:** Use with .macro-detail for proper styling
// **Overrides:** 2 properties (color, line-height)
//
// **Visual:**
// - color: `var(--ui-color-surface-on)` 🎨
// **Typography:**
// - line-height: `1.6`
const MacroDetailDocstring = "macro-detail__docstring"

// **Base:** .macro-detail
// **Context:** Use with .macro-detail for proper styling
// **Overrides:** 5 properties (border-top, font-family, font-size, margin-top, padding-top)
//
// **Visual:**
// - border-top: `var(--ui-border-sm) solid var(--ui-color-outline)` 🎨
// **Layout:**
// - margin-top: `var(--ui-space-lg)` 🎨
// - padding-top: `var(--ui-space-sm)` 🎨
// **Typography:**
// - font-family: `var(--ui-font-code)` 🎨
// - font-size: `var(--ui-type-size-sm)` 🎨
const MacroDetailLocation = "macro-detail__location"

// **Base:** .macro-detail
// **Context:** Use with .macro-detail for proper styling
// **Overrides:** 2 properties (color, font-weight)
//
// **Visual:**
// - color: `var(--ui-color-primary)` 🎨
// **Typography:**
// - font-weight: `var(--ui-weight-medium)` 🎨
const MacroDetailRequired = "macro-detail__required"

// **Base:** .macro-detail
// **Context:** Use with .macro-detail for proper styling
// **Overrides:** 6 properties (color, font-size, font-weight, margin, margin-bottom, text-transform)
//
// **Visual:**
// - color: `var(--ui-color-surface-variant-on)` 🎨
// **Layout:**
// - margin: `0 0 var(--ui-space-md) 0` 🎨
// - margin-bottom: `var(--ui-space-lg)` 🎨
// **Typography:**
// - font-size: `var(--ui-type-size-sm)` 🎨
// - font-weight: `var(--ui-weight-semibold)` 🎨
// - text-transform: `uppercase`
const MacroDetailSection = "macro-detail__section"

// **Base:** .macro-detail
// **Context:** Use with .macro-detail for proper styling
// **Overrides:** 8 properties (background, border-radius, display, font-family, font-size, font-weight, margin-bottom, padding)
//
// **Visual:**
// - background: `var(--ui-color-surface-container-high)` 🎨
// - border-radius: `var(--ui-radius-md)` 🎨
// **Layout:**
// - display: `inline-block`
// - margin-bottom: `var(--ui-space-lg)` 🎨
// - padding: `var(--ui-space-sm) var(--ui-space-sm)` 🎨
// **Typography:**
// - font-family: `var(--ui-font-code)` 🎨
// - font-size: `var(--ui-type-size-lg)` 🎨
// - font-weight: `var(--ui-weight-medium)` 🎨
const MacroDetailSignature = "macro-detail__signature"

// **Base:** .macro-detail
// **Context:** Use with .macro-detail for proper styling
// **Overrides:** 9 properties (background, border, border-radius, font-family, font-size, line-height, overflow-x, padding, white-space)
//
// **Visual:**
// - background: `var(--ui-color-surface-container)` 🎨
// - border: `var(--ui-border-sm) solid var(--ui-color-outline-variant)` 🎨
// - border-radius: `var(--ui-radius-lg)` 🎨
// **Layout:**
// - overflow-x: `auto`
// - padding: `var(--ui-space-sm)` 🎨
// **Typography:**
// - font-family: `inherit`
// - font-size: `var(--ui-type-size-sm)` 🎨
// - line-height: `1.6`
// - white-space: `pre`
const MacroDetailSource = "macro-detail__source"

// **Visual:**
// - border-radius: `var(--ui-radius-sm)` 🎨
// - color: `var(--ui-color-surface-on)` 🎨
// **Layout:**
// - align-items: `center`
// - cursor: `pointer`
// - display: `flex`
// - gap: `var(--ui-space-sm)` 🎨
// - padding: `var(--ui-space-xs) var(--ui-space-sm)` 🎨
// **Typography:**
// - font-family: `var(--ui-font-code)` 🎨
// - font-size: `var(--ui-type-size-sm)` 🎨
// - text-decoration: `none`
//
// **Interactions:**
// - `:hover`: Changes background to `var(--ui-color-surface-container-high)`
const MacroFunction = "macro-function"

// **Base:** .macro-function
// **Context:** Use with .macro-function for proper styling
// **Overrides:** 4 properties (background, border-radius, height, width)
//
// **Visual:**
// - background: `var(--ui-color-primary-on)` 🎨
// - border-radius: `50%`
// **Layout:**
// - height: `6px`
// - width: `6px`
const MacroFunctionDocIndicator = "macro-function__doc-indicator"

// **Base:** .macro-function
// **Context:** Use with .macro-function for proper styling
// **Overrides:** 1 properties (flex)
//
// **Layout:**
// - flex: `1`
const MacroFunctionName = "macro-function__name"

// **Base:** .macro-function
// **Context:** Use with .macro-function for proper styling
// **Overrides:** 2 properties (background, color)
//
// **Visual:**
// - background: `var(--ui-color-primary-on)` 🎨
// - color: `var(--ui-color-primary-on)` 🎨
const MacroFunctionSelected = "macro-function--selected"

// **Layout:**
// - content: `"-"`
// - cursor: `pointer`
// - display: `none`
// - list-style: `none`
// - margin-bottom: `var(--ui-space-xs)` 🎨
const MacroNamespace = "macro-namespace"

// **Base:** .macro-namespace
// **Context:** Use with .macro-namespace for proper styling
// **Overrides:** 2 properties (color, font-size)
//
// **Visual:**
// - color: `var(--ui-color-surface-variant-on)` 🎨
// **Typography:**
// - font-size: `var(--ui-type-size-xs)` 🎨
const MacroNamespaceCount = "macro-namespace__count"

// **Base:** .macro-namespace
// **Context:** Use with .macro-namespace for proper styling
// **Overrides:** 3 properties (border-left, margin-left, padding-left)
//
// **Visual:**
// - border-left: `1px solid var(--ui-color-outline)` 🎨
// **Layout:**
// - margin-left: `var(--ui-space-sm)` 🎨
// - padding-left: `var(--ui-space-xs)` 🎨
const MacroNamespaceFunctions = "macro-namespace__functions"

// **Base:** .macro-namespace
// **Context:** Use with .macro-namespace for proper styling
// **Overrides:** 7 properties (align-items, border-radius, display, font-size, font-weight, gap, padding)
//
// **Visual:**
// - border-radius: `var(--ui-radius-sm)` 🎨
// **Layout:**
// - align-items: `center`
// - content: `"-"`
// - display: `flex`
// - gap: `var(--ui-space-sm)` 🎨
// - padding: `6px var(--ui-space-sm)` 🎨
// **Typography:**
// - font-size: `var(--ui-type-size-sm)` 🎨
// - font-weight: `var(--ui-weight-medium)` 🎨
//
// **Interactions:**
// - `:hover`: Changes background to `var(--ui-color-surface-container-high)`
const MacroNamespaceHeader = "macro-namespace__header"

// **Base:** .macro-namespace
// **Context:** Use with .macro-namespace for proper styling
// **Overrides:** 3 properties (font-family, opacity, width)
//
// **Visual:**
// - opacity: `0.7`
// **Layout:**
// - content: `"-"`
// - width: `var(--ui-space-sm)` 🎨
// **Typography:**
// - font-family: `var(--ui-font-code)` 🎨
const MacroNamespaceIcon = "macro-namespace__icon"

// **Base:** .macro-namespace
// **Context:** Use with .macro-namespace for proper styling
// **Overrides:** 1 properties (flex)
//
// **Layout:**
// - flex: `1`
const MacroNamespaceName = "macro-namespace__name"

// **Layout:**
// - flex: `1`
// - overflow-y: `auto`
// - padding: `var(--ui-space-sm)` 🎨
const MacroTree = "macro-tree"

// **Visual:**
// - color: `var(--ui-color-surface-variant-on)` 🎨
// **Layout:**
// - align-items: `center`
// - display: `flex`
// - flex-direction: `column`
// - height: `100%`
// - justify-content: `center`
// - [+1 more layout properties]
// **Typography:**
// - text-align: `center`
const MacrosEmpty = "macros-empty"

// **Layout:**
// - display: `grid`
// - gap: `0`
// - grid-template-columns: `280px 1fr`
// - height: `100%`
// - overflow: `hidden`
const MacrosPage = "macros-page"

// **Base:** .macros-page
// **Context:** Use with .macros-page for proper styling
// **Overrides:** 2 properties (overflow-y, padding)
//
// **Layout:**
// - overflow-y: `auto`
// - padding: `var(--ui-space-lg)` 🎨
const MacrosPageDetail = "macros-page__detail"

// **Base:** .macros-page
// **Context:** Use with .macros-page for proper styling
// **Overrides:** 5 properties (border-bottom, font-size, font-weight, margin, padding)
//
// **Visual:**
// - border-bottom: `var(--ui-border-sm) solid var(--ui-color-outline)` 🎨
// **Layout:**
// - margin: `0 0 var(--ui-space-xs) 0` 🎨
// - padding: `var(--ui-space-sm)` 🎨
// **Typography:**
// - font-size: `var(--ui-type-size-lg)` 🎨
// - font-weight: `var(--ui-weight-semibold)` 🎨
const MacrosPageHeader = "macros-page__header"

// **Base:** .macros-page
// **Context:** Use with .macros-page for proper styling
// **Overrides:** 4 properties (background, border-right, display, flex-direction)
//
// **Visual:**
// - background: `var(--ui-color-surface-container)` 🎨
// - border-right: `var(--ui-border-sm) solid var(--ui-color-outline)` 🎨
// **Layout:**
// - display: `flex`
// - flex-direction: `column`
// - overflow: `hidden`
const MacrosPageSidebar = "macros-page__sidebar"

// **Typography:**
// - font-size: `var(--ui-type-size-sm)` 🎨
const TextSm = "text-sm"

