// Code generated by cssgen. DO NOT EDIT.
//
// Component: Runs
// Generated: 2026-02-05 21:28:45

package cssgen

// Runs component styles
//
// For the full CSS class registry, see styles.gen.go

// **Visual:**
// - border-bottom: `var(--ui-border-sm) solid var(--ui-color-outline)` 🎨
// **Layout:**
// - align-items: `center`
// - display: `flex`
// - gap: `var(--ui-space-sm)` 🎨
// - padding: `var(--ui-space-sm) var(--ui-space-md)` 🎨
// **Typography:**
// - font-size: `var(--ui-type-size-sm)` 🎨
//
// **Interactions:**
// - `:last-child`: Changes border-bottom to `none`
const ModelRunCard = "model-run-card"

// **Base:** .model-run-card
// **Context:** Use with .model-run-card for proper styling
// **Overrides:** 4 properties (flex-shrink, justify-content, position, width)
//
// **Layout:**
// - align-items: `center`
// - display: `flex`
// - flex-shrink: `0`
// - justify-content: `center`
// - position: `relative`
// - [+1 more layout properties]
const ModelRunCardConnector = "model-run-card__connector"

// **Base:** .model-run-card
// **Context:** Use with .model-run-card for proper styling
// **Overrides:** 5 properties (background, border-radius, flex, height, overflow)
//
// **Visual:**
// - background: `var(--ui-color-surface-variant)` 🎨
// - border-radius: `2px`
// **Layout:**
// - flex: `1`
// - height: `var(--ui-space-xs)` 🎨
// - overflow: `hidden`
const ModelRunCardDurationBar = "model-run-card__duration-bar"

// **Base:** .model-run-card
// **Context:** Use with .model-run-card for proper styling
// **Overrides:** 4 properties (background, border-radius, height, transition)
//
// **Visual:**
// - background: `var(--ui-color-primary)` 🎨
// - border-radius: `2px`
// **Layout:**
// - height: `100%`
// **Effects:**
// - transition: `width 0.3s ease`
const ModelRunCardDurationFill = "model-run-card__duration-fill"

// **Base:** .model-run-card
// **Context:** Use with .model-run-card for proper styling
// **Overrides:** 5 properties (color, font-family, font-size, min-width, text-align)
//
// **Visual:**
// - color: `var(--ui-color-surface-variant-on)` 🎨
// **Layout:**
// - min-width: `45px`
// **Typography:**
// - font-family: `var(--ui-font-code)` 🎨
// - font-size: `var(--ui-type-size-xs)` 🎨
// - text-align: `right`
const ModelRunCardDurationText = "model-run-card__duration-text"

// **Base:** .model-run-card
// **Context:** Use with .model-run-card for proper styling
// **Overrides:** 5 properties (background, border-radius, color, margin-top, width)
//
// **Visual:**
// - background: `var(--status-failed-bg)`
// - border-radius: `var(--ui-radius-sm)` 🎨
// - color: `var(--status-failed)`
// **Layout:**
// - margin-top: `var(--ui-space-sm)` 🎨
// - padding: `var(--ui-space-sm) var(--ui-space-md)` 🎨
// - width: `100%`
// **Typography:**
// - font-size: `var(--ui-type-size-sm)` 🎨
const ModelRunCardError = "model-run-card__error"

// **Base:** .model-run-card
// **Context:** Use with .model-run-card for proper styling
// **Overrides:** 1 properties (word-break)
//
// **Typography:**
// - word-break: `break-word`
const ModelRunCardErrorText = "model-run-card__error-text"

// **Base:** .model-run-card
// **Context:** Use with .model-run-card for proper styling
// **Overrides:** 1 properties (background)
//
// **Visual:**
// - background: `var(--status-failed-bg)`
const ModelRunCardFailed = "model-run-card--failed"

// **Base:** .model-run-card
// **Context:** Use with .model-run-card for proper styling
// **Overrides:** 2 properties (flex, min-width)
//
// **Layout:**
// - flex: `1`
// - min-width: `0`
const ModelRunCardInfo = "model-run-card__info"

// **Base:** .model-run-card
// **Context:** Use with .model-run-card for proper styling
// **Overrides:** 7 properties (background, bottom, left, position, top, transform, width)
//
// **Visual:**
// - background: `var(--ui-color-outline)` 🎨
// **Layout:**
// - bottom: `-8px`
// - left: `50%`
// - position: `absolute`
// - top: `-8px`
// - width: `1px`
// **Effects:**
// - transform: `translateX(-50%)`
const ModelRunCardLine = "model-run-card__line"

// **Base:** .model-run-card__line
// **Context:** Use with .model-run-card__line for proper styling
// **Overrides:** 1 properties (bottom)
//
// **Layout:**
// - bottom: `50%`
const ModelRunCardLineLast = "model-run-card__line--last"

// **Base:** .model-run-card
// **Context:** Use with .model-run-card for proper styling
// **Overrides:** 3 properties (color, font-weight, text-decoration)
//
// **Visual:**
// - color: `var(--ui-color-surface-on)` 🎨
// **Typography:**
// - font-weight: `var(--ui-weight-medium)` 🎨
// - text-decoration: `none`
//
// **Interactions:**
// - `:hover`: Changes color to `var(--ui-color-primary)`, text-decoration to `underline`
const ModelRunCardName = "model-run-card__name"

// **Base:** .model-run-card
// **Context:** Use with .model-run-card for proper styling
// **Overrides:** 1 properties (background)
//
// **Visual:**
// - background: `var(--status-running-bg)`
const ModelRunCardRunning = "model-run-card--running"

// **Base:** .model-run-card
// **Context:** Use with .model-run-card for proper styling
// **Overrides:** 1 properties (opacity)
//
// **Visual:**
// - opacity: `0.7`
const ModelRunCardSkipped = "model-run-card--skipped"

// **Base:** .model-run-card
// **Context:** Use with .model-run-card for proper styling
// **Overrides:** 1 properties (flex-shrink)
//
// **Layout:**
// - flex-shrink: `0`
const ModelRunCardStatus = "model-run-card__status"

// **Base:** .model-run-card
// **Context:** Use with .model-run-card for proper styling
// **Overrides:** 2 properties (flex-shrink, min-width)
//
// **Layout:**
// - align-items: `center`
// - display: `flex`
// - flex-shrink: `0`
// - gap: `var(--ui-space-sm)` 🎨
// - min-width: `120px`
const ModelRunCardTiming = "model-run-card__timing"

// **Layout:**
// - max-width: `150px`
// - overflow: `hidden`
// **Typography:**
// - font-family: `var(--ui-font-code)` 🎨
// - text-overflow: `ellipsis`
// - white-space: `nowrap`
const ModelRunName = "model-run-name"

// **Visual:**
// - background: `color-mix(in oklch, var(--ui-color-error) 5%, transparent)` 🎨
const ModelRunRowFailed = "model-run-row--failed"

// **Visual:**
// - background: `color-mix(in oklch, var(--ui-color-primary) 5%, transparent)` 🎨
const ModelRunRowRunning = "model-run-row--running"

// **Visual:**
// - color: `var(--ui-color-surface-variant-on)` 🎨
// **Typography:**
// - font-family: `var(--ui-font-code)` 🎨
// - text-align: `right`
const ModelRunRows = "model-run-rows"

// **Visual:**
// - border-radius: `3px`
// **Layout:**
// - display: `inline-block`
// - padding: `1px 6px`
// **Typography:**
// - font-size: `var(--ui-type-size-xs)` 🎨
// - font-weight: `var(--ui-weight-semibold)` 🎨
// - text-transform: `uppercase`
const ModelRunStatus = "model-run-status"

// **Base:** .model-run-status
// **Context:** Use with .model-run-status for proper styling
// **Overrides:** 2 properties (background, color)
//
// **Visual:**
// - background: `color-mix(in oklch, var(--ui-color-error) 15%, transparent)` 🎨
// - color: `var(--ui-color-error)` 🎨
const ModelRunStatusFailed = "model-run-status--failed"

// **Base:** .model-run-status
// **Context:** Use with .model-run-status for proper styling
// **Overrides:** 2 properties (background, color)
//
// **Visual:**
// - background: `color-mix(in oklch, var(--chart-4, oklch(0.692 0.2041 42.4293)) 15%, transparent)`
// - color: `var(--chart-4, oklch(0.692 0.2041 42.4293))`
const ModelRunStatusPending = "model-run-status--pending"

// **Base:** .model-run-status
// **Context:** Use with .model-run-status for proper styling
// **Overrides:** 2 properties (background, color)
//
// **Visual:**
// - background: `color-mix(in oklch, var(--ui-color-primary) 15%, transparent)` 🎨
// - color: `var(--ui-color-primary)` 🎨
const ModelRunStatusRunning = "model-run-status--running"

// **Base:** .model-run-status
// **Context:** Use with .model-run-status for proper styling
// **Overrides:** 2 properties (background, color)
//
// **Visual:**
// - background: `color-mix(in oklch, var(--ui-color-surface-variant-on) 15%, transparent)` 🎨
// - color: `var(--ui-color-surface-variant-on)` 🎨
const ModelRunStatusSkipped = "model-run-status--skipped"

// **Base:** .model-run-status
// **Context:** Use with .model-run-status for proper styling
// **Overrides:** 2 properties (background, color)
//
// **Visual:**
// - background: `color-mix(in oklch, var(--ui-color-tertiary) 15%, transparent)` 🎨
// - color: `var(--ui-color-tertiary)` 🎨
const ModelRunStatusSuccess = "model-run-status--success"

// **Visual:**
// - color: `var(--ui-color-surface-variant-on)` 🎨
// **Typography:**
// - font-family: `var(--ui-font-code)` 🎨
// - text-align: `right`
const ModelRunTime = "model-run-time"

// **Visual:**
// - border-bottom: `var(--ui-border-sm) solid var(--ui-color-outline)` 🎨
// - border-collapse: `collapse`
// - color: `var(--ui-color-surface-variant-on)` 🎨
// **Layout:**
// - padding: `var(--ui-space-sm)` 🎨
// - width: `100%`
// **Typography:**
// - font-size: `var(--ui-type-size-xs)` 🎨
// - font-weight: `var(--ui-weight-semibold)` 🎨
// - text-align: `left`
// - text-transform: `uppercase`
const ModelRunsTable = "model-runs-table"

// **Typography:**
// - text-align: `right`
const RunActions = "run-actions"

// **Visual:**
// - color: `var(--ui-color-surface-variant-on)` 🎨
// **Layout:**
// - align-items: `center`
// - display: `flex`
// - flex-direction: `column`
// - justify-content: `center`
// - min-height: `200px`
// - [+1 more layout properties]
// **Typography:**
// - text-align: `center`
const RunDetailEmpty = "run-detail-empty"

// **Base:** .run-detail-empty
// **Context:** Use with .run-detail-empty for proper styling
// **Overrides:** 3 properties (color, margin-top, text-decoration)
//
// **Visual:**
// - color: `var(--ui-color-primary)` 🎨
// **Layout:**
// - margin-top: `var(--ui-space-sm)` 🎨
// **Typography:**
// - text-decoration: `none`
//
// **Interactions:**
// - `:hover`: Changes text-decoration to `underline`
const RunDetailEmptyLink = "run-detail-empty__link"

// **Visual:**
// - color: `var(--ui-color-error)` 🎨
// **Layout:**
// - max-width: `250px`
// **Typography:**
// - text-align: `right`
// - word-break: `break-word`
const RunDetailError = "run-detail__error"

// **Visual:**
// - border-bottom: `var(--ui-border-sm) solid var(--ui-color-outline)` 🎨
// **Layout:**
// - align-items: `center`
// - display: `flex`
// - justify-content: `space-between`
// - margin: `0`
// - margin-bottom: `var(--ui-space-sm)` 🎨
// - [+1 more layout properties]
// **Typography:**
// - font-size: `var(--ui-type-size-sm)` 🎨
// - font-weight: `var(--ui-weight-semibold)` 🎨
const RunDetailHeader = "run-detail__header"

// **Visual:**
// - border-bottom: `var(--ui-border-sm) solid var(--ui-color-outline)` 🎨
// **Layout:**
// - padding-bottom: `var(--ui-space-sm)` 🎨
const RunDetailHeader2 = "run-detail-header"

// **Base:** .run-detail-header
// **Context:** Use with .run-detail-header for proper styling
// **Overrides:** 2 properties (display, gap)
//
// **Layout:**
// - display: `flex`
// - gap: `var(--ui-space-xs)` 🎨
const RunDetailHeaderItem = "run-detail-header__item"

// **Base:** .run-detail-header
// **Context:** Use with .run-detail-header for proper styling
// **Overrides:** 1 properties (color)
//
// **Visual:**
// - color: `var(--ui-color-surface-variant-on)` 🎨
const RunDetailHeaderKey = "run-detail-header__key"

// **Base:** .run-detail-header
// **Context:** Use with .run-detail-header for proper styling
// **Overrides:** 2 properties (font-size, font-weight)
//
// **Typography:**
// - font-size: `var(--ui-type-size-lg)` 🎨
// - font-weight: `var(--ui-weight-semibold)` 🎨
const RunDetailHeaderLabel = "run-detail-header__label"

// **Base:** .run-detail-header
// **Context:** Use with .run-detail-header for proper styling
// **Overrides:** 5 properties (color, display, flex-wrap, font-size, gap)
//
// **Visual:**
// - color: `var(--ui-color-surface-variant-on)` 🎨
// **Layout:**
// - display: `flex`
// - flex-wrap: `wrap`
// - gap: `var(--ui-space-sm)` 🎨
// **Typography:**
// - font-size: `var(--ui-type-size-sm)` 🎨
const RunDetailHeaderMeta = "run-detail-header__meta"

// **Base:** .run-detail-header
// **Context:** Use with .run-detail-header for proper styling
// **Overrides:** 5 properties (background, border-radius, height, margin-top, overflow)
//
// **Visual:**
// - background: `var(--ui-color-surface-variant)` 🎨
// - border-radius: `2px`
// **Layout:**
// - height: `var(--ui-space-xs)` 🎨
// - margin-top: `var(--ui-space-md)` 🎨
// - overflow: `hidden`
const RunDetailHeaderProgress = "run-detail-header__progress"

// **Base:** .run-detail-header
// **Context:** Use with .run-detail-header for proper styling
// **Overrides:** 2 properties (border-radius, height)
//
// **Visual:**
// - border-radius: `2px`
// **Layout:**
// - height: `100%`
const RunDetailHeaderProgressBar = "run-detail-header__progress-bar"

// **Base:** .run-detail-header__progress-bar
// **Context:** Use with .run-detail-header__progress-bar for proper styling
// **Overrides:** 3 properties (animation, background, background-size)
//
// **Visual:**
// - background: `linear-gradient( 90deg, var(--status-running), color-mix(in oklch, var(--status-running) 50%, transparent), var(--status-running) )`
// - background-size: `200% 100%`
// **Effects:**
// - animation: `progress 1.5s ease-in-out infinite`
const RunDetailHeaderProgressBarRunning = "run-detail-header__progress-bar--running"

// **Base:** .run-detail-header
// **Context:** Use with .run-detail-header for proper styling
// **Overrides:** 4 properties (align-items, display, gap, margin-bottom)
//
// **Layout:**
// - align-items: `center`
// - display: `flex`
// - gap: `var(--ui-space-md)` 🎨
// - margin-bottom: `var(--ui-space-sm)` 🎨
const RunDetailHeaderTitle = "run-detail-header__title"

// **Base:** .run-detail-header
// **Context:** Use with .run-detail-header for proper styling
// **Overrides:** 2 properties (color, font-family)
//
// **Visual:**
// - color: `var(--ui-color-surface-on)` 🎨
// **Typography:**
// - font-family: `var(--ui-font-code)` 🎨
const RunDetailHeaderValue = "run-detail-header__value"

// **Layout:**
// - display: `flex`
// - flex-direction: `column`
// - gap: `var(--ui-space-sm)` 🎨
// - margin-bottom: `var(--ui-space-lg)` 🎨
const RunDetailInfo = "run-detail__info"

// **Visual:**
// - color: `var(--ui-color-surface-variant-on)` 🎨
const RunDetailLabel = "run-detail__label"

// **Layout:**
// - margin: `0 0 var(--ui-space-md) 0` 🎨
// **Typography:**
// - font-size: `var(--ui-type-size-base)` 🎨
// - font-weight: `var(--ui-weight-semibold)` 🎨
const RunDetailModels = "run-detail__models"

// **Layout:**
// - align-items: `center`
// - display: `flex`
// - justify-content: `space-between`
// **Typography:**
// - font-size: `var(--ui-type-size-sm)` 🎨
const RunDetailRow = "run-detail__row"

// **Base:** .run-detail__row
// **Context:** Use with .run-detail__row for proper styling
// **Overrides:** 3 properties (border-top, margin-top, padding-top)
//
// **Visual:**
// - border-top: `var(--ui-border-sm) solid var(--ui-color-outline)` 🎨
// **Layout:**
// - margin-top: `var(--ui-space-sm)` 🎨
// - padding-top: `var(--ui-space-sm)` 🎨
const RunDetailRowError = "run-detail__row--error"

// **Layout:**
// - display: `flex`
// - flex-direction: `column`
// - gap: `var(--ui-space-sm)` 🎨
const RunDetailTiered = "run-detail-tiered"

// **Base:** .run-detail-tiered
// **Context:** Use with .run-detail-tiered for proper styling
// **Overrides:** 6 properties (background, border, border-radius, color, font-size, padding)
//
// **Visual:**
// - background: `var(--status-failed-bg)`
// - border: `var(--ui-border-sm) solid var(--status-failed)` 🎨
// - border-radius: `var(--ui-radius-md)` 🎨
// - color: `var(--status-failed)`
// **Layout:**
// - padding: `var(--ui-space-md)` 🎨
// **Typography:**
// - font-size: `var(--ui-type-size-sm)` 🎨
const RunDetailTieredError = "run-detail-tiered__error"

// **Base:** .run-detail-tiered
// **Context:** Use with .run-detail-tiered for proper styling
//
// **Layout:**
// - display: `flex`
// - flex-direction: `column`
// - gap: `var(--ui-space-sm)` 🎨
const RunDetailTieredTiers = "run-detail-tiered__tiers"

// **Typography:**
// - font-family: `var(--ui-font-code)` 🎨
// - font-size: `var(--ui-type-size-sm)` 🎨
const RunDetailValue = "run-detail__value"

// **Visual:**
// - color: `var(--ui-color-surface-variant-on)` 🎨
// **Typography:**
// - font-family: `var(--ui-font-code)` 🎨
// - font-size: `var(--ui-type-size-sm)` 🎨
const RunDuration = "run-duration"

// **Typography:**
// - font-family: `var(--ui-font-code)` 🎨
// - font-size: `var(--ui-type-size-sm)` 🎨
const RunEnv = "run-env"

// **Visual:**
// - border-bottom: `var(--ui-border-sm) solid var(--ui-color-outline)` 🎨
// - color: `inherit`
// **Layout:**
// - align-items: `center`
// - cursor: `pointer`
// - display: `flex`
// - justify-content: `space-between`
// - padding: `var(--ui-space-md) var(--ui-space-sm)` 🎨
// **Typography:**
// - text-decoration: `none`
// **Effects:**
// - transition: `background var(--ui-duration-fast) var(--ui-ease-default)` 🎨
//
// **Interactions:**
// - `:hover`: Changes background to `var(--ui-color-surface-variant)`
// - `:focus`: Changes outline to `2px solid var(--ui-color-primary)`, outline-offset to `-2px`
const RunListCard = "run-list-card"

// **Base:** .run-list-card
// **Context:** Use with .run-list-card for proper styling
// **Overrides:** 1 properties (border-left-color)
//
// **Visual:**
// - border-left-color: `var(--status-success)`
const RunListCardCompleted = "run-list-card--completed"

// **Base:** .run-list-card
// **Context:** Use with .run-list-card for proper styling
// **Overrides:** 5 properties (background, border-radius, color, font-size, padding)
//
// **Visual:**
// - background: `var(--ui-color-surface-variant)` 🎨
// - border-radius: `var(--ui-space-xs)` 🎨
// - color: `var(--ui-color-surface-variant-on)` 🎨
// **Layout:**
// - padding: `1px 6px`
// **Typography:**
// - font-size: `var(--ui-type-size-xs)` 🎨
const RunListCardEnv = "run-list-card__env"

// **Base:** .run-list-card
// **Context:** Use with .run-list-card for proper styling
// **Overrides:** 1 properties (border-left-color)
//
// **Visual:**
// - border-left-color: `var(--status-failed)`
const RunListCardFailed = "run-list-card--failed"

// **Base:** .run-list-card
// **Context:** Use with .run-list-card for proper styling
// **Overrides:** 4 properties (color, font-family, font-size, font-weight)
//
// **Visual:**
// - color: `var(--ui-color-surface-on)` 🎨
// **Typography:**
// - font-family: `var(--ui-font-code)` 🎨
// - font-size: `var(--ui-type-size-sm)` 🎨
// - font-weight: `var(--ui-weight-medium)` 🎨
const RunListCardId = "run-list-card__id"

// **Base:** .run-list-card
// **Context:** Use with .run-list-card for proper styling
// **Overrides:** 2 properties (flex, min-width)
//
// **Layout:**
// - flex: `1`
// - min-width: `0`
const RunListCardInfo = "run-list-card__info"

// **Base:** .run-list-card
// **Context:** Use with .run-list-card for proper styling
// **Overrides:** 3 properties (flex, gap, min-width)
//
// **Layout:**
// - align-items: `center`
// - display: `flex`
// - flex: `1`
// - gap: `var(--ui-space-md)` 🎨
// - min-width: `0`
const RunListCardMain = "run-list-card__main"

// **Base:** .run-list-card
// **Context:** Use with .run-list-card for proper styling
// **Overrides:** 3 properties (color, font-size, gap)
//
// **Visual:**
// - color: `var(--ui-color-surface-variant-on)` 🎨
// **Layout:**
// - align-items: `center`
// - display: `flex`
// - gap: `var(--ui-space-md)` 🎨
// **Typography:**
// - font-size: `var(--ui-type-size-sm)` 🎨
const RunListCardMeta = "run-list-card__meta"

// **Base:** .run-list-card
// **Context:** Use with .run-list-card for proper styling
// **Overrides:** 1 properties (border-left-color)
//
// **Visual:**
// - border-left-color: `var(--status-running)`
const RunListCardRunning = "run-list-card--running"

// **Base:** .run-list-card
// **Context:** Use with .run-list-card for proper styling
// **Overrides:** 3 properties (background, border-left, padding-left)
//
// **Visual:**
// - background: `color-mix(in oklch, var(--ui-color-primary) 8%, transparent)` 🎨
// - border-left: `3px solid var(--ui-color-primary)` 🎨
// **Layout:**
// - padding-left: `13px`
const RunListCardSelected = "run-list-card--selected"

// **Base:** .run-list-card
// **Context:** Use with .run-list-card for proper styling
// **Overrides:** 1 properties (flex-shrink)
//
// **Layout:**
// - flex-shrink: `0`
const RunListCardStats = "run-list-card__stats"

// **Base:** .run-list-card
// **Context:** Use with .run-list-card for proper styling
// **Overrides:** 1 properties (flex-shrink)
//
// **Layout:**
// - flex-shrink: `0`
const RunListCardStatus = "run-list-card__status"

// **Base:** .run-list-card
// **Context:** Use with .run-list-card for proper styling
// **Overrides:** 2 properties (gap, margin-bottom)
//
// **Layout:**
// - align-items: `center`
// - display: `flex`
// - gap: `var(--ui-space-sm)` 🎨
// - margin-bottom: `var(--ui-space-xs)` 🎨
const RunListCardTitle = "run-list-card__title"

// **Layout:**
// - align-items: `center`
// - display: `flex`
// - gap: `var(--ui-space-sm)` 🎨
const RunMiniStats = "run-mini-stats"

// **Base:** .run-mini-stats
// **Context:** Use with .run-mini-stats for proper styling
// **Overrides:** 3 properties (font-family, font-size, gap)
//
// **Layout:**
// - align-items: `center`
// - display: `flex`
// - gap: `3px`
// **Typography:**
// - font-family: `var(--ui-font-code)` 🎨
// - font-size: `var(--ui-type-size-sm)` 🎨
const RunMiniStatsItem = "run-mini-stats__item"

// **Base:** .run-mini-stats__item
// **Context:** Use with .run-mini-stats__item for proper styling
// **Overrides:** 1 properties (color)
//
// **Visual:**
// - color: `var(--status-failed)`
const RunMiniStatsItemFailed = "run-mini-stats__item--failed"

// **Base:** .run-mini-stats__item
// **Context:** Use with .run-mini-stats__item for proper styling
// **Overrides:** 1 properties (color)
//
// **Visual:**
// - color: `var(--status-pending)`
const RunMiniStatsItemPending = "run-mini-stats__item--pending"

// **Base:** .run-mini-stats__item
// **Context:** Use with .run-mini-stats__item for proper styling
// **Overrides:** 1 properties (color)
//
// **Visual:**
// - color: `var(--status-running)`
const RunMiniStatsItemRunning = "run-mini-stats__item--running"

// **Base:** .run-mini-stats__item
// **Context:** Use with .run-mini-stats__item for proper styling
// **Overrides:** 1 properties (color)
//
// **Visual:**
// - color: `var(--status-skipped)`
const RunMiniStatsItemSkipped = "run-mini-stats__item--skipped"

// **Base:** .run-mini-stats__item
// **Context:** Use with .run-mini-stats__item for proper styling
// **Overrides:** 1 properties (color)
//
// **Visual:**
// - color: `var(--status-success)`
const RunMiniStatsItemSuccess = "run-mini-stats__item--success"

// **Visual:**
// - background: `color-mix(in oklch, var(--ui-color-error) 5%, transparent)` 🎨
const RunRowFailed = "run-row--failed"

// **Visual:**
// - background: `color-mix(in oklch, var(--ui-color-primary) 5%, transparent)` 🎨
const RunRowRunning = "run-row--running"

// **Visual:**
// - border-radius: `var(--ui-radius-sm)` 🎨
// **Layout:**
// - display: `inline-block`
// - padding: `2px var(--ui-space-sm)` 🎨
// **Typography:**
// - font-size: `var(--ui-type-size-xs)` 🎨
// - font-weight: `var(--ui-weight-semibold)` 🎨
// - text-transform: `uppercase`
const RunStatus = "run-status"

// **Base:** .run-status
// **Context:** Use with .run-status for proper styling
// **Overrides:** 2 properties (background, color)
//
// **Visual:**
// - background: `color-mix(in oklch, var(--ui-color-surface-variant-on) 15%, transparent)` 🎨
// - color: `var(--ui-color-surface-variant-on)` 🎨
const RunStatusCancelled = "run-status--cancelled"

// **Base:** .run-status
// **Context:** Use with .run-status for proper styling
// **Overrides:** 2 properties (background, color)
//
// **Visual:**
// - background: `color-mix(in oklch, var(--ui-color-tertiary) 15%, transparent)` 🎨
// - color: `var(--ui-color-tertiary)` 🎨
const RunStatusCompleted = "run-status--completed"

// **Base:** .run-status
// **Context:** Use with .run-status for proper styling
// **Overrides:** 2 properties (background, color)
//
// **Visual:**
// - background: `color-mix(in oklch, var(--ui-color-error) 15%, transparent)` 🎨
// - color: `var(--ui-color-error)` 🎨
const RunStatusFailed = "run-status--failed"

// **Base:** .run-status
// **Context:** Use with .run-status for proper styling
// **Overrides:** 2 properties (background, color)
//
// **Visual:**
// - background: `color-mix(in oklch, var(--ui-color-primary) 15%, transparent)` 🎨
// - color: `var(--ui-color-primary)` 🎨
const RunStatusRunning = "run-status--running"

// **Visual:**
// - background: `var(--ui-color-surface-variant)` 🎨
// - border-radius: `var(--ui-radius-md)` 🎨
// **Layout:**
// - display: `flex`
// - flex-wrap: `wrap`
// - gap: `var(--ui-space-sm)` 🎨
// - padding: `var(--ui-space-md) var(--ui-space-sm)` 🎨
// **Typography:**
// - font-size: `var(--ui-type-size-sm)` 🎨
const RunSummaryBar = "run-summary-bar"

// **Base:** .run-summary-bar
// **Context:** Use with .run-summary-bar for proper styling
// **Overrides:** 2 properties (align-items, gap)
//
// **Layout:**
// - align-items: `center`
// - display: `flex`
// - gap: `6px`
const RunSummaryBarItem = "run-summary-bar__item"

// **Base:** .run-summary-bar__item
// **Context:** Use with .run-summary-bar__item for proper styling
// **Overrides:** 1 properties (color)
//
// **Visual:**
// - color: `var(--status-failed)`
const RunSummaryBarItemFailed = "run-summary-bar__item--failed"

// **Base:** .run-summary-bar__item
// **Context:** Use with .run-summary-bar__item for proper styling
// **Overrides:** 1 properties (color)
//
// **Visual:**
// - color: `var(--status-pending)`
const RunSummaryBarItemPending = "run-summary-bar__item--pending"

// **Base:** .run-summary-bar__item
// **Context:** Use with .run-summary-bar__item for proper styling
// **Overrides:** 1 properties (color)
//
// **Visual:**
// - color: `var(--status-running)`
const RunSummaryBarItemRunning = "run-summary-bar__item--running"

// **Base:** .run-summary-bar__item
// **Context:** Use with .run-summary-bar__item for proper styling
// **Overrides:** 1 properties (color)
//
// **Visual:**
// - color: `var(--status-skipped)`
const RunSummaryBarItemSkipped = "run-summary-bar__item--skipped"

// **Base:** .run-summary-bar__item
// **Context:** Use with .run-summary-bar__item for proper styling
// **Overrides:** 1 properties (color)
//
// **Visual:**
// - color: `var(--status-success)`
const RunSummaryBarItemSuccess = "run-summary-bar__item--success"

// **Visual:**
// - color: `var(--ui-color-surface-variant-on)` 🎨
// **Typography:**
// - font-size: `var(--ui-type-size-sm)` 🎨
const RunTime = "run-time"

// **Layout:**
// - display: `flex`
// - flex-direction: `column`
const RunsCardList = "runs-card-list"

// **Layout:**
// - display: `grid`
// - gap: `var(--ui-space-sm)` 🎨
// - grid-template-columns: `380px 1fr`
// - height: `calc(100vh - 180px)`
// - min-height: `400px`
const RunsContainer = "runs-container"

// **Visual:**
// - background: `var(--ui-color-surface-container)` 🎨
// - border: `var(--ui-border-sm) solid var(--ui-color-outline)` 🎨
// - border-radius: `var(--ui-radius-lg)` 🎨
// **Layout:**
// - overflow: `auto`
// - overflow-y: `auto`
// - padding: `var(--ui-space-sm)` 🎨
const RunsDetailContainer = "runs-detail-container"

// **Visual:**
// - color: `var(--ui-color-surface-variant-on)` 🎨
// **Layout:**
// - padding: `48px`
// **Typography:**
// - text-align: `center`
const RunsEmpty = "runs-empty"

// **Layout:**
// - margin: `0 0 var(--ui-space-xs) 0` 🎨
// - margin-bottom: `var(--ui-space-lg)` 🎨
// **Typography:**
// - font-size: `var(--ui-type-size-2xl)` 🎨
// - font-weight: `var(--ui-weight-semibold)` 🎨
const RunsHeader = "runs-header"

// **Visual:**
// - background: `var(--ui-color-surface-container)` 🎨
// - border: `var(--ui-border-sm) solid var(--ui-color-outline)` 🎨
// - border-radius: `var(--ui-radius-lg)` 🎨
// **Layout:**
// - overflow: `auto`
// - overflow-y: `auto`
const RunsListContainer = "runs-list-container"

// **Layout:**
// - display: `flex`
// - flex-direction: `column`
// - height: `100%`
// - padding: `var(--ui-space-sm)` 🎨
const RunsPage = "runs-page"

// **Visual:**
// - background: `var(--ui-color-surface-container)` 🎨
// - border-bottom: `var(--ui-border-sm) solid var(--ui-color-outline)` 🎨
// - border-collapse: `collapse`
// - color: `var(--ui-color-surface-variant-on)` 🎨
// **Layout:**
// - padding: `var(--ui-space-md)` 🎨
// - position: `sticky`
// - top: `0`
// - width: `100%`
// - z-index: `1`
// **Typography:**
// - font-size: `var(--ui-type-size-xs)` 🎨
// - font-weight: `var(--ui-weight-semibold)` 🎨
// - text-align: `left`
// - text-transform: `uppercase`
//
// **Interactions:**
// - `:hover`: Changes background to `var(--ui-color-surface-variant)`
const RunsTable = "runs-table"

// **Visual:**
// - border-radius: `50%`
// **Layout:**
// - align-items: `center`
// - display: `block`
// - justify-content: `center`
const StatusIcon = "status-icon"

// **Base:** .status-icon
// **Context:** Use with .status-icon for proper styling
// **Overrides:** 1 properties (color)
//
// **Visual:**
// - color: `var(--status-failed)`
const StatusIconFailed = "status-icon--failed"

// **Base:** .status-icon
// **Context:** Use with .status-icon for proper styling
// **Overrides:** 2 properties (height, width)
//
// **Layout:**
// - height: `18px`
// - width: `18px`
const StatusIconLg = "status-icon--lg"

// **Base:** .status-icon
// **Context:** Use with .status-icon for proper styling
// **Overrides:** 2 properties (height, width)
//
// **Layout:**
// - height: `14px`
// - width: `14px`
const StatusIconMd = "status-icon--md"

// **Base:** .status-icon
// **Context:** Use with .status-icon for proper styling
// **Overrides:** 1 properties (color)
//
// **Visual:**
// - color: `var(--status-pending)`
const StatusIconPending = "status-icon--pending"

// **Base:** .status-icon
// **Context:** Use with .status-icon for proper styling
// **Overrides:** 1 properties (color)
//
// **Visual:**
// - color: `var(--status-running)`
const StatusIconRunning = "status-icon--running"

// **Base:** .status-icon
// **Context:** Use with .status-icon for proper styling
// **Overrides:** 1 properties (color)
//
// **Visual:**
// - color: `var(--status-skipped)`
const StatusIconSkipped = "status-icon--skipped"

// **Base:** .status-icon
// **Context:** Use with .status-icon for proper styling
// **Overrides:** 2 properties (height, width)
//
// **Layout:**
// - height: `10px`
// - width: `10px`
const StatusIconSm = "status-icon--sm"

// **Base:** .status-icon
// **Context:** Use with .status-icon for proper styling
// **Overrides:** 1 properties (animation)
//
// **Effects:**
// - animation: `spin 1s linear infinite`
const StatusIconSpinning = "status-icon--spinning"

// **Base:** .status-icon
// **Context:** Use with .status-icon for proper styling
// **Overrides:** 1 properties (color)
//
// **Visual:**
// - color: `var(--status-success)`
const StatusIconSuccess = "status-icon--success"

// **Visual:**
// - border: `var(--ui-border-sm) solid var(--ui-color-outline)` 🎨
// - border-radius: `var(--ui-radius-md)` 🎨
// **Layout:**
// - overflow: `hidden`
// **Effects:**
// - transform: `rotate(90deg)`
const TierGroup = "tier-group"

// **Base:** .tier-group
// **Context:** Use with .tier-group for proper styling
// **Overrides:** 2 properties (height, width)
//
// **Layout:**
// - height: `var(--ui-space-sm)` 🎨
// - width: `var(--ui-space-sm)` 🎨
const TierGroupArrow = "tier-group__arrow"

// **Base:** .tier-group
// **Context:** Use with .tier-group for proper styling
// **Overrides:** 1 properties (padding)
//
// **Layout:**
// - padding: `0`
const TierGroupContent = "tier-group__content"

// **Base:** .tier-group
// **Context:** Use with .tier-group for proper styling
// **Overrides:** 1 properties (font-family)
//
// **Typography:**
// - font-family: `var(--ui-font-code)` 🎨
const TierGroupCount = "tier-group__count"

// **Base:** .tier-group
// **Context:** Use with .tier-group for proper styling
// **Overrides:** 1 properties (font-family)
//
// **Typography:**
// - font-family: `var(--ui-font-code)` 🎨
const TierGroupDuration = "tier-group__duration"

// **Base:** .tier-group
// **Context:** Use with .tier-group for proper styling
// **Overrides:** 8 properties (align-items, background, cursor, display, gap, list-style, padding, user-select)
//
// **Visual:**
// - background: `var(--ui-color-surface-variant)` 🎨
// **Layout:**
// - align-items: `center`
// - cursor: `pointer`
// - display: `none`
// - gap: `var(--ui-space-sm)` 🎨
// - list-style: `none`
// - [+2 more layout properties]
const TierGroupHeader = "tier-group__header"

// **Base:** .tier-group
// **Context:** Use with .tier-group for proper styling
// **Overrides:** 3 properties (flex, font-size, font-weight)
//
// **Layout:**
// - flex: `1`
// **Typography:**
// - font-size: `var(--ui-type-size-sm)` 🎨
// - font-weight: `var(--ui-weight-medium)` 🎨
const TierGroupLabel = "tier-group__label"

// **Base:** .tier-group
// **Context:** Use with .tier-group for proper styling
// **Overrides:** 2 properties (display, flex-direction)
//
// **Layout:**
// - display: `flex`
// - flex-direction: `column`
const TierGroupModels = "tier-group__models"

// **Base:** .tier-group
// **Context:** Use with .tier-group for proper styling
// **Overrides:** 5 properties (align-items, color, display, font-size, gap)
//
// **Visual:**
// - color: `var(--ui-color-surface-variant-on)` 🎨
// **Layout:**
// - align-items: `center`
// - display: `flex`
// - gap: `var(--ui-space-md)` 🎨
// **Typography:**
// - font-size: `var(--ui-type-size-sm)` 🎨
const TierGroupStats = "tier-group__stats"

// **Base:** .tier-group
// **Context:** Use with .tier-group for proper styling
// **Overrides:** 5 properties (color, flex-shrink, height, transition, width)
//
// **Visual:**
// - color: `var(--ui-color-surface-variant-on)` 🎨
// **Layout:**
// - flex-shrink: `0`
// - height: `var(--ui-space-sm)` 🎨
// - width: `var(--ui-space-sm)` 🎨
// **Effects:**
// - transform: `rotate(90deg)`
// - transition: `transform 0.2s ease`
const TierGroupToggle = "tier-group__toggle"

