// Code generated by cssgen. DO NOT EDIT.
//
// Component: Side Panel
// Generated: 2026-02-05 21:33:16

package cssgen

// Side Panel component styles
//
// For the full CSS class registry, see styles.gen.go

// **Visual:**
// - background: `transparent`
// - border: `none`
// - border-radius: `var(--ui-radius-sm)` 🎨
// - color: `var(--ui-color-surface-variant-on)` 🎨
// **Layout:**
// - align-items: `center`
// - cursor: `pointer`
// - display: `flex`
// - height: `20px`
// - justify-content: `center`
// - [+1 more layout properties]
// **Typography:**
// - font-size: `var(--ui-type-size-md)` 🎨
// - line-height: `var(--ui-leading-none)` 🎨
//
// **Interactions:**
// - `:hover`: Changes background to `var(--ui-color-surface-variant)`, color to `var(--ui-color-surface-on)`
const SidePanelClose = "side-panel__close"

// **Visual:**
// - background: `var(--ui-color-outline)` 🎨
// - border-radius: `var(--ui-radius-sm)` 🎨
// **Layout:**
// - flex: `1`
// - overflow-y: `auto`
// - padding: `var(--ui-space-sm)` 🎨
// - width: `var(--ui-space-sm)` 🎨
//
// **Interactions:**
// - `:hover`: Changes background to `var(--ui-color-surface-variant-on)`
const SidePanelContent = "side-panel__content"

// **Visual:**
// - background: `var(--ui-color-surface-container)` 🎨
// - border-bottom: `var(--ui-border-sm) solid var(--ui-color-outline)` 🎨
// **Layout:**
// - align-items: `center`
// - display: `flex`
// - justify-content: `space-between`
// - padding: `var(--ui-space-sm) var(--ui-space-md)` 🎨
const SidePanelHeader = "side-panel__header"

// **Visual:**
// - color: `var(--ui-color-surface-variant-on)` 🎨
// **Typography:**
// - font-size: `var(--ui-type-size-xs)` 🎨
// - font-weight: `var(--ui-weight-semibold)` 🎨
// - letter-spacing: `0.5px`
// - text-transform: `uppercase`
const SidePanelTitle = "side-panel__title"

// **Layout:**
// - display: `flex`
// - flex: `1`
// - flex-direction: `column`
// - overflow: `hidden`
const SidePanelView = "side-panel__view"

// **Visual:**
// - background: `var(--ui-color-background)` 🎨
// - border-right: `var(--ui-border-sm) solid var(--ui-color-outline)` 🎨
// **Layout:**
// - display: `none`
// - flex-direction: `column`
// - min-width: `var(--side-panel-width)`
// - overflow: `hidden`
// - width: `var(--side-panel-width)`
// **Effects:**
// - transition: `width var(--ui-duration-fast) var(--ui-ease-default), min-width var(--ui-duration-fast) var(--ui-ease-default), opacity var(--ui-duration-fast) var(--ui-ease-default)` 🎨
const UiSidePanel = "ui-side-panel"

