// Code generated by cssgen. DO NOT EDIT.
//
// Component: Base Transitions
// Generated: 2026-02-05 21:33:16

package cssgen

// Base Transitions component styles
//
// For the full CSS class registry, see styles.gen.go

// **Effects:**
// - animation-name: `slide-out-to-right`
const NavBack = "nav-back"

// **Effects:**
// - animation-name: `slide-out-to-left`
const NavForward = "nav-forward"

// **Visual:**
// - background: `var(--ui-color-surface-container)` 🎨
// - border-left: `var(--ui-border-sm) solid var(--ui-color-outline)` 🎨
// **Layout:**
// - overflow-y: `auto`
// - padding: `var(--ui-space-md)` 🎨
// - view-transition-name: `context-panel`
// - width: `var(--context-panel-width)`
const UiContextPanel = "ui-context-panel"

// **Visual:**
// - background: `var(--ui-color-surface-container)` 🎨
// - border-bottom: `var(--ui-border-sm) solid var(--ui-color-outline)` 🎨
// **Layout:**
// - align-items: `center`
// - display: `flex`
// - gap: `var(--ui-space-sm)` 🎨
// - height: `var(--header-height)`
// - padding: `0 var(--ui-space-sm)` 🎨
// - [+1 more layout properties]
const UiHeader = "ui-header"

// **Visual:**
// - background: `var(--ui-color-surface-container)` 🎨
// - border-right: `var(--ui-border-sm) solid var(--ui-color-outline)` 🎨
// **Layout:**
// - display: `flex`
// - flex-direction: `column`
// - overflow: `hidden`
// - view-transition-name: `sidebar`
// - width: `var(--side-panel-width)`
const UiSidebar = "ui-sidebar"

