// Code generated by cssgen. DO NOT EDIT.
//
// Component: Base Layout
// Generated: 2026-02-06 10:18:37

package cssgen

// Base Layout component styles
//
// For the full CSS class registry, see styles.gen.go

// **Layout:**
// - display: `flex`
// - flex-direction: `column`
// - height: `100vh`
// - overflow: `hidden`
const UiBody = "ui-body"

// **Visual:**
// - background: `var(--ui-color-background)` 🎨
// **Layout:**
// - flex: `1`
// - margin-bottom: `var(--ui-space-lg)` 🎨
// - min-width: `0`
// - overflow: `auto`
// - padding: `var(--ui-space-lg)` 🎨
// - [+2 more layout properties]
// **Typography:**
// - font-size: `var(--ui-type-size-2xl)` 🎨
// - font-weight: `var(--ui-weight-semibold)` 🎨
const UiContent = "ui-content"

// **Base:** .ui-content
// **Context:** Use with .ui-content for proper styling
// **Overrides:** 2 properties (padding, padding-bottom)
//
// **Layout:**
// - padding: `var(--ui-space-sm)` 🎨
// - padding-bottom: `calc(var(--log-drawer-height) + var(--ui-space-sm))` 🎨
const UiContentFull = "ui-content--full"

// **Layout:**
// - display: `flex`
// - flex-direction: `column`
// - height: `100%`
const UiLayout = "ui-layout"

// **Layout:**
// - display: `flex`
// - height: `calc(100vh - var(--header-height))`
// - overflow: `hidden`
const UiMain = "ui-main"

