// Code generated by cssgen. DO NOT EDIT.
//
// Component: Tables
// Generated: 2026-02-06 10:18:37

package cssgen

// Tables component styles
//
// For the full CSS class registry, see styles.gen.go

// **Visual:**
// - background: `var(--ui-color-surface-container)` 🎨
// - border: `var(--ui-border-sm) solid var(--ui-color-outline-variant)` 🎨
// - border-radius: `var(--ui-radius-lg)` 🎨
// **Layout:**
// - overflow: `hidden`
const DataPreview = "data-preview"

// **Base:** .data-preview
// **Context:** Use with .data-preview for proper styling
// **Overrides:** 2 properties (color, font-size)
//
// **Visual:**
// - color: `var(--ui-color-surface-variant-on)` 🎨
// **Typography:**
// - font-size: `var(--ui-type-size-sm)` 🎨
const DataPreviewCount = "data-preview__count"

// **Base:** .data-preview
// **Context:** Use with .data-preview for proper styling
// **Overrides:** 6 properties (align-items, background, border-bottom, display, justify-content, padding)
//
// **Visual:**
// - background: `var(--ui-color-surface-variant)` 🎨
// - border-bottom: `var(--ui-border-sm) solid var(--ui-color-outline-variant)` 🎨
// **Layout:**
// - align-items: `center`
// - display: `flex`
// - justify-content: `space-between`
// - padding: `var(--ui-space-md) var(--ui-space-sm)` 🎨
const DataPreviewHeader = "data-preview__header"

// **Base:** .data-preview
// **Context:** Use with .data-preview for proper styling
// **Overrides:** 17 properties (background, border-bottom, border-collapse, color, font-family, font-size, font-weight, max-width, padding, position, text-align, text-overflow, text-transform, top, white-space, width, z-index)
//
// **Visual:**
// - background: `var(--ui-color-surface-variant)` 🎨
// - border-bottom: `var(--ui-border-sm) solid var(--ui-color-outline-variant)` 🎨
// - border-collapse: `collapse`
// - color: `var(--ui-color-surface-variant-on)` 🎨
// **Layout:**
// - max-width: `300px`
// - overflow: `hidden`
// - padding: `var(--ui-space-sm) var(--ui-space-md)` 🎨
// - position: `sticky`
// - top: `0`
// - [+2 more layout properties]
// **Typography:**
// - font-family: `var(--ui-font-code)` 🎨
// - font-size: `var(--ui-type-size-xs)` 🎨
// - font-weight: `var(--ui-weight-semibold)` 🎨
// - text-align: `left`
// - text-overflow: `ellipsis`
// - [+2 more typography properties]
const DataPreviewTable = "data-preview__table"

// **Base:** .data-preview
// **Context:** Use with .data-preview for proper styling
// **Overrides:** 3 properties (max-height, overflow-x, overflow-y)
//
// **Layout:**
// - max-height: `400px`
// - overflow-x: `auto`
// - overflow-y: `auto`
const DataPreviewTableWrapper = "data-preview__table-wrapper"

// **Base:** .data-preview
// **Context:** Use with .data-preview for proper styling
// **Overrides:** 4 properties (color, font-size, font-weight, text-transform)
//
// **Visual:**
// - color: `var(--ui-color-surface-variant-on)` 🎨
// **Typography:**
// - font-size: `var(--ui-type-size-sm)` 🎨
// - font-weight: `var(--ui-weight-semibold)` 🎨
// - text-transform: `uppercase`
const DataPreviewTitle = "data-preview__title"

