// Code generated by cssgen. DO NOT EDIT.
//
// Component: Sidebar
// Generated: 2026-02-05 21:33:16

package cssgen

// Sidebar component styles
//
// For the full CSS class registry, see styles.gen.go

// **Base:** .ui-sidebar
// **Context:** Use with .ui-sidebar for proper styling
// **Overrides:** 2 properties (border-bottom, padding)
//
// **Visual:**
// - border-bottom: `var(--ui-border-sm) solid var(--ui-color-outline)` 🎨
// **Layout:**
// - padding: `var(--ui-space-md)` 🎨
const UiSidebarSection = "ui-sidebar__section"

// **Base:** .ui-sidebar
// **Context:** Use with .ui-sidebar for proper styling
// **Overrides:** 5 properties (color, font-size, font-weight, margin-bottom, text-transform)
//
// **Visual:**
// - color: `var(--ui-color-surface-variant-on)` 🎨
// **Layout:**
// - margin-bottom: `var(--ui-space-sm)` 🎨
// **Typography:**
// - font-size: `var(--ui-type-size-xs)` 🎨
// - font-weight: `var(--ui-weight-semibold)` 🎨
// - text-transform: `uppercase`
const UiSidebarTitle = "ui-sidebar__title"

// **Base:** .ui-sidebar
// **Context:** Use with .ui-sidebar for proper styling
// **Overrides:** 3 properties (flex, overflow-y, padding)
//
// **Layout:**
// - flex: `1`
// - overflow-y: `auto`
// - padding: `var(--ui-space-sm)` 🎨
const UiSidebarTree = "ui-sidebar__tree"

