// Code generated by cssgen. DO NOT EDIT.
//
// Component: Model Detail
// Generated: 2026-02-05 21:33:16

package cssgen

// Model Detail component styles
//
// For the full CSS class registry, see styles.gen.go

// **Visual:**
// - background: `var(--ui-color-error)` 🎨
// - border-radius: `var(--ui-radius-md)` 🎨
// - color: `var(--ui-color-error-on)` 🎨
// **Layout:**
// - padding: `var(--ui-space-md) var(--ui-space-sm)` 🎨
// **Typography:**
// - font-size: `var(--ui-type-size-sm)` 🎨
const ErrorMessage = "error-message"

// **Layout:**
// - max-width: `900px`
const ModelDetail = "model-detail"

// **Base:** .model-detail
// **Context:** Use with .model-detail for proper styling
// **Overrides:** 3 properties (display, gap, margin-bottom)
//
// **Layout:**
// - display: `flex`
// - gap: `var(--ui-space-sm)` 🎨
// - margin-bottom: `var(--ui-space-sm)` 🎨
const ModelDetailActions = "model-detail__actions"

// **Base:** .model-detail
// **Context:** Use with .model-detail for proper styling
// **Overrides:** 6 properties (background, border, border-radius, font-size, font-weight, padding)
//
// **Visual:**
// - background: `var(--ui-color-surface-variant)` 🎨
// - border: `var(--ui-border-sm) solid var(--ui-color-outline)` 🎨
// - border-radius: `var(--ui-radius-sm)` 🎨
// **Layout:**
// - padding: `2px var(--ui-space-sm)` 🎨
// **Typography:**
// - font-size: `var(--ui-type-size-sm)` 🎨
// - font-weight: `var(--ui-weight-medium)` 🎨
const ModelDetailBadge = "model-detail__badge"

// **Base:** .model-detail
// **Context:** Use with .model-detail for proper styling
// **Overrides:** 1 properties (margin-top)
//
// **Layout:**
// - margin-top: `var(--ui-space-sm)` 🎨
const ModelDetailContent = "model-detail__content"

// **Base:** .model-detail
// **Context:** Use with .model-detail for proper styling
// **Overrides:** 3 properties (color, line-height, margin-bottom)
//
// **Visual:**
// - color: `var(--ui-color-surface-variant-on)` 🎨
// **Layout:**
// - margin-bottom: `var(--ui-space-sm)` 🎨
// **Typography:**
// - line-height: `1.6`
const ModelDetailDescription = "model-detail__description"

// **Base:** .model-detail
// **Context:** Use with .model-detail for proper styling
// **Overrides:** 3 properties (color, padding, text-align)
//
// **Visual:**
// - color: `var(--ui-color-surface-variant-on)` 🎨
// **Layout:**
// - padding: `var(--ui-space-xl)` 🎨
// **Typography:**
// - text-align: `center`
const ModelDetailEmpty = "model-detail--empty"

// **Base:** .model-detail
// **Context:** Use with .model-detail for proper styling
// **Overrides:** 1 properties (margin-bottom)
//
// **Layout:**
// - margin-bottom: `var(--ui-space-sm)` 🎨
const ModelDetailHeader = "model-detail__header"

// **Base:** .model-detail
// **Context:** Use with .model-detail for proper styling
// **Overrides:** 5 properties (align-items, display, flex-wrap, gap, margin-bottom)
//
// **Layout:**
// - align-items: `center`
// - display: `flex`
// - flex-wrap: `wrap`
// - gap: `var(--ui-space-md)` 🎨
// - margin-bottom: `var(--ui-space-sm)` 🎨
const ModelDetailMeta = "model-detail__meta"

// **Base:** .model-detail
// **Context:** Use with .model-detail for proper styling
// **Overrides:** 2 properties (color, font-size)
//
// **Visual:**
// - color: `var(--ui-color-surface-variant-on)` 🎨
// **Typography:**
// - font-size: `var(--ui-type-size-sm)` 🎨
const ModelDetailOwner = "model-detail__owner"

// **Base:** .model-detail
// **Context:** Use with .model-detail for proper styling
// **Overrides:** 3 properties (color, font-family, font-size)
//
// **Visual:**
// - color: `var(--ui-color-surface-variant-on)` 🎨
// **Typography:**
// - font-family: `var(--ui-font-code)` 🎨
// - font-size: `var(--ui-type-size-sm)` 🎨
const ModelDetailPath = "model-detail__path"

// **Base:** .model-detail
// **Context:** Use with .model-detail for proper styling
// **Overrides:** 1 properties (margin-top)
//
// **Layout:**
// - margin-top: `var(--ui-space-lg)` 🎨
const ModelDetailPreview = "model-detail__preview"

// **Base:** .model-detail
// **Context:** Use with .model-detail for proper styling
// **Overrides:** 2 properties (color, font-size)
//
// **Visual:**
// - color: `var(--ui-color-surface-variant-on)` 🎨
// **Typography:**
// - font-size: `var(--ui-type-size-sm)` 🎨
const ModelDetailSchema = "model-detail__schema"

// **Base:** .model-detail
// **Context:** Use with .model-detail for proper styling
// **Overrides:** 1 properties (margin-top)
//
// **Layout:**
// - margin-top: `var(--ui-space-lg)` 🎨
const ModelDetailSql = "model-detail__sql"

// **Base:** .model-detail
// **Context:** Use with .model-detail for proper styling
// **Overrides:** 10 properties (background, border, border-radius, font-family, font-size, line-height, overflow-x, padding, white-space, word-break)
//
// **Visual:**
// - background: `var(--ui-color-surface-container)` 🎨
// - border: `var(--ui-border-sm) solid var(--ui-color-outline)` 🎨
// - border-radius: `var(--ui-radius-lg)` 🎨
// **Layout:**
// - overflow-x: `auto`
// - padding: `var(--ui-space-sm)` 🎨
// **Typography:**
// - font-family: `inherit`
// - font-size: `var(--ui-type-size-sm)` 🎨
// - line-height: `1.6`
// - white-space: `pre-wrap`
// - word-break: `break-word`
const ModelDetailSqlCode = "model-detail__sql-code"

// **Base:** .model-detail
// **Context:** Use with .model-detail for proper styling
// **Overrides:** 8 properties (align-items, color, display, font-size, font-weight, justify-content, margin-bottom, text-transform)
//
// **Visual:**
// - color: `var(--ui-color-surface-variant-on)` 🎨
// **Layout:**
// - align-items: `center`
// - display: `flex`
// - justify-content: `space-between`
// - margin-bottom: `var(--ui-space-sm)` 🎨
// **Typography:**
// - font-size: `var(--ui-type-size-sm)` 🎨
// - font-weight: `var(--ui-weight-semibold)` 🎨
// - text-transform: `uppercase`
const ModelDetailSqlHeader = "model-detail__sql-header"

// **Base:** .model-detail
// **Context:** Use with .model-detail for proper styling
// **Overrides:** 5 properties (background, border-radius, color, font-size, padding)
//
// **Visual:**
// - background: `var(--ui-color-primary)` 🎨
// - border-radius: `var(--ui-radius-sm)` 🎨
// - color: `var(--ui-color-primary-on)` 🎨
// **Layout:**
// - padding: `2px var(--ui-space-sm)` 🎨
// **Typography:**
// - font-size: `var(--ui-type-size-xs)` 🎨
const ModelDetailTag = "model-detail__tag"

// **Base:** .model-detail
// **Context:** Use with .model-detail for proper styling
// **Overrides:** 4 properties (display, flex-wrap, gap, margin-bottom)
//
// **Layout:**
// - display: `flex`
// - flex-wrap: `wrap`
// - gap: `6px`
// - margin-bottom: `var(--ui-space-sm)` 🎨
const ModelDetailTags = "model-detail__tags"

// **Base:** .model-detail
// **Context:** Use with .model-detail for proper styling
// **Overrides:** 3 properties (font-size, font-weight, margin)
//
// **Layout:**
// - margin: `0 0 var(--ui-space-xs) 0` 🎨
// **Typography:**
// - font-size: `var(--ui-type-size-2xl)` 🎨
// - font-weight: `var(--ui-weight-semibold)` 🎨
const ModelDetailTitle = "model-detail__title"

// **Visual:**
// - background: `var(--ui-color-surface-container)` 🎨
// - border: `var(--ui-border-sm) solid var(--ui-color-outline)` 🎨
// - border-radius: `var(--ui-radius-lg)` 🎨
// **Layout:**
// - overflow-x: `auto`
// - padding: `var(--ui-space-sm)` 🎨
// **Typography:**
// - font-family: `inherit`
// - font-size: `var(--ui-type-size-sm)` 🎨
// - line-height: `1.6`
// - white-space: `pre-wrap`
// - word-break: `break-word`
const SqlCode = "sql-code"

