// Code generated by cssgen. DO NOT EDIT.
//
// Component: Sql Editor
// Generated: 2026-02-05 21:28:45

package cssgen

// Sql Editor component styles
//
// For the full CSS class registry, see styles.gen.go

// **Visual:**
// - background: `var(--ui-color-surface-variant-on)` 🎨
// - border-radius: `var(--ui-radius-sm)` 🎨
// - outline: `2px solid var(--ui-color-primary)` 🎨
// **Layout:**
// - height: `var(--ui-space-sm)` 🎨
// - max-height: `300px`
// - min-height: `180px`
// - outline-offset: `-2px`
// - overflow: `hidden`
// - [+1 more layout properties]
const SqlEditorContainer = "sql-editor__container"

