// Code generated by cssgen. DO NOT EDIT.
//
// Component: Activity Bar
// Generated: 2026-02-05 21:33:16

package cssgen

// Activity Bar component styles
//
// For the full CSS class registry, see styles.gen.go

// **Visual:**
// - background: `var(--ui-color-primary)` 🎨
// - border-radius: `0 var(--ui-radius-xs) var(--ui-radius-xs) 0` 🎨
// - color: `var(--ui-color-surface-on)` 🎨
// **Layout:**
// - content: `''`
// - height: `var(--ui-space-lg)` 🎨
// - left: `0`
// - position: `absolute`
// - top: `50%`
// - [+1 more layout properties]
// **Effects:**
// - transform: `translateY(-50%)`
const Active = "active"

// **Layout:**
// - align-items: `center`
// - display: `flex`
// - flex-direction: `column`
// - gap: `var(--ui-space-xs)` 🎨
// - padding: `var(--ui-space-xs) 0` 🎨
//
// **Interactions:**
// - `:last-child`: Changes border-bottom to `var(--ui-border-sm) solid var(--ui-color-outline)`, margin-bottom to `var(--ui-space-xs)`, padding-bottom to `var(--ui-space-sm)`
const ActivityBarGroup = "activity-bar__group"

// **Visual:**
// - background: `var(--ui-color-primary)` 🎨
// - border: `none`
// - border-radius: `0 var(--ui-radius-xs) var(--ui-radius-xs) 0` 🎨
// - color: `var(--ui-color-surface-on)` 🎨
// **Layout:**
// - align-items: `center`
// - content: `''`
// - cursor: `pointer`
// - display: `flex`
// - height: `var(--ui-space-lg)` 🎨
// - [+5 more layout properties]
// **Typography:**
// - text-decoration: `none`
// **Effects:**
// - transform: `translateY(-50%)`
// - transition: `all var(--ui-duration-fast) var(--ui-ease-default)` 🎨
//
// **Interactions:**
// - `:hover`: Changes background to `var(--ui-color-surface-variant)`, color to `var(--ui-color-surface-on)`
const ActivityBarItem = "activity-bar__item"

// **Base:** .activity-bar__item
// **Context:** Use with .activity-bar__item for proper styling
// **Overrides:** 7 properties (border-radius, bottom, color, height, left, transform, width)
//
// **Visual:**
// - background: `var(--ui-color-primary)` 🎨
// - border-radius: `var(--ui-radius-full)` 🎨
// - color: `var(--ui-color-primary)` 🎨
// **Layout:**
// - bottom: `2px`
// - content: `''`
// - height: `var(--ui-space-xs)` 🎨
// - left: `50%`
// - position: `absolute`
// - [+1 more layout properties]
// **Effects:**
// - transform: `translateX(-50%)`
const ActivityBarItemCurrent = "activity-bar__item--current"

// **Layout:**
// - flex: `1`
const ActivityBarSpacer = "activity-bar__spacer"

// **Visual:**
// - background: `var(--ui-color-surface-container)` 🎨
// - border-right: `var(--ui-border-sm) solid var(--ui-color-outline)` 🎨
// **Layout:**
// - display: `flex`
// - flex-direction: `column`
// - min-width: `var(--activity-bar-width)`
// - padding: `var(--ui-space-sm) 0` 🎨
// - width: `var(--activity-bar-width)`
// - [+1 more layout properties]
const UiActivityBar = "ui-activity-bar"

