// Code generated by cssgen. DO NOT EDIT.
//
// Component: Header
// Generated: 2026-02-06 10:18:37

package cssgen

// Header component styles
//
// For the full CSS class registry, see styles.gen.go

// **Visual:**
// - background: `color-mix(in oklch, var(--ui-color-surface-container) 80%, transparent)` 🎨
// - border: `var(--ui-border-sm) solid var(--ui-color-outline)` 🎨
// - border-radius: `var(--ui-radius-lg)` 🎨
// - box-shadow: `var(--ui-shadow-lg)` 🎨
// **Layout:**
// - align-items: `center`
// - display: `flex`
// - gap: `var(--ui-space-xs)` 🎨
// - padding: `var(--ui-space-xs)` 🎨
// **Effects:**
// - backdrop-filter: `blur(12px)`
// - transition: `background-color var(--ui-duration-fast) var(--ui-ease-out), border-color var(--ui-duration-fast) var(--ui-ease-out)` 🎨
const ThemeControls = "theme-controls"

// **Visual:**
// - background: `transparent`
// - border: `none`
// - border-radius: `var(--ui-radius-md)` 🎨
// - color: `var(--ui-color-surface-on)` 🎨
// **Layout:**
// - align-items: `center`
// - cursor: `pointer`
// - display: `flex`
// - height: `18px`
// - justify-content: `center`
// - [+2 more layout properties]
// **Effects:**
// - transition: `all var(--ui-duration-fast) var(--ui-ease-default)` 🎨
//
// **Interactions:**
// - `:hover`: Changes background to `var(--ui-color-surface-container-high)`
// - `:active`: Changes transform to `scale(0.92)`
const ThemeToggle = "theme-toggle"

// **Base:** .ui-header
// **Context:** Use with .ui-header for proper styling
// **Overrides:** 2 properties (position, right)
//
// **Layout:**
// - align-items: `center`
// - display: `flex`
// - gap: `var(--ui-space-sm)` 🎨
// - position: `absolute`
// - right: `var(--ui-space-sm)` 🎨
const UiHeaderActions = "ui-header__actions"

// **Base:** .ui-header
// **Context:** Use with .ui-header for proper styling
// **Overrides:** 6 properties (color, font-size, font-weight, left, position, text-decoration)
//
// **Visual:**
// - color: `inherit`
// **Layout:**
// - left: `var(--ui-space-sm)` 🎨
// - position: `absolute`
// **Typography:**
// - font-size: `var(--ui-type-size-md)` 🎨
// - font-weight: `var(--ui-weight-semibold)` 🎨
// - text-decoration: `none`
const UiHeaderLogo = "ui-header__logo"

// **Base:** .ui-header
// **Context:** Use with .ui-header for proper styling
// **Overrides:** 8 properties (background, border, border-radius, color, font-size, max-width, padding, width)
//
// **Visual:**
// - background: `var(--ui-color-surface-container-high)` 🎨
// - border: `var(--ui-border-sm) solid var(--ui-color-outline)` 🎨
// - border-radius: `var(--ui-radius-md)` 🎨
// - color: `var(--ui-color-surface-variant-on)` 🎨
// **Layout:**
// - max-width: `500px`
// - padding: `6px var(--ui-space-md)` 🎨
// - width: `100%`
// **Typography:**
// - font-size: `var(--ui-type-size-sm)` 🎨
//
// **Interactions:**
// - `:focus`: Changes border-color to `var(--ui-color-primary)`, outline to `none`
const UiHeaderSearch = "ui-header__search"

