// Code generated by cssgen. DO NOT EDIT.
//
// Component: Tree
// Generated: 2026-02-06 10:18:37

package cssgen

// Tree component styles
//
// For the full CSS class registry, see styles.gen.go

// **Layout:**
// - content: `"-"`
// - display: `none`
// - list-style: `none`
// - margin-bottom: `2px`
const TreeFolder = "tree-folder"

// **Base:** .tree-folder
// **Context:** Use with .tree-folder for proper styling
// **Overrides:** 3 properties (border-left, margin-left, padding-left)
//
// **Visual:**
// - border-left: `var(--ui-border-sm) solid var(--ui-color-outline-variant)` 🎨
// **Layout:**
// - margin-left: `var(--ui-space-sm)` 🎨
// - padding-left: `var(--ui-space-xs)` 🎨
const TreeFolderChildren = "tree-folder__children"

// **Visual:**
// - border-radius: `var(--ui-radius-sm)` 🎨
// - color: `var(--ui-color-surface-on)` 🎨
// **Layout:**
// - align-items: `center`
// - cursor: `pointer`
// - display: `flex`
// - gap: `var(--ui-space-sm)` 🎨
// - padding: `var(--ui-space-xs) var(--ui-space-sm)` 🎨
// **Typography:**
// - font-size: `var(--ui-type-size-sm)` 🎨
// - text-decoration: `none`
//
// **Interactions:**
// - `:hover`: Changes background to `var(--ui-color-surface-container-high)`
// - `:focus-visible`: Changes outline to `var(--ui-border-md) solid var(--ui-color-primary)`, outline-offset to `-2px`
const TreeItem = "tree-item"

// **Base:** .tree-item
// **Context:** Use with .tree-item for proper styling
// **Overrides:** 4 properties (background, border-left, font-weight, padding-left)
//
// **Visual:**
// - background: `var(--ui-color-surface-bright)` 🎨
// - border-left: `var(--ui-border-lg) solid var(--ui-color-primary)` 🎨
// - color: `var(--ui-color-surface-on)` 🎨
// **Layout:**
// - padding-left: `calc(var(--ui-space-sm) - var(--ui-border-lg))` 🎨
// **Typography:**
// - font-weight: `var(--ui-weight-medium)` 🎨
const TreeItemActive = "tree-item--active"

// **Base:** .tree-item
// **Context:** Use with .tree-item for proper styling
// **Overrides:** 3 properties (color, font-size, margin-left)
//
// **Visual:**
// - color: `var(--ui-color-surface-variant-on)` 🎨
// **Layout:**
// - margin-left: `auto`
// **Typography:**
// - font-size: `var(--ui-type-size-xs)` 🎨
const TreeItemCount = "tree-item__count"

// **Base:** .tree-item
// **Context:** Use with .tree-item for proper styling
// **Overrides:** 1 properties (font-weight)
//
// **Typography:**
// - font-weight: `var(--ui-weight-medium)` 🎨
const TreeItemFolder = "tree-item--folder"

// **Base:** .tree-item
// **Context:** Use with .tree-item for proper styling
// **Overrides:** 6 properties (content, font-family, height, opacity, text-align, width)
//
// **Visual:**
// - opacity: `0.7`
// **Layout:**
// - content: `"-"`
// - height: `16px`
// - width: `16px`
// **Typography:**
// - font-family: `var(--ui-font-code)` 🎨
// - text-align: `center`
const TreeItemIcon = "tree-item__icon"

// **Base:** .tree-item
// **Context:** Use with .tree-item for proper styling
// **Overrides:** 1 properties (padding-left)
//
// **Layout:**
// - padding-left: `var(--ui-space-sm)` 🎨
const TreeItemModel = "tree-item--model"

// **Base:** .tree-item
// **Context:** Use with .tree-item for proper styling
// **Overrides:** 4 properties (background, border-left, font-weight, padding-left)
//
// **Visual:**
// - background: `var(--ui-color-surface-bright)` 🎨
// - border-left: `var(--ui-border-lg) solid var(--ui-color-primary)` 🎨
// - color: `var(--ui-color-surface-on)` 🎨
// **Layout:**
// - padding-left: `calc(var(--ui-space-sm) - var(--ui-border-lg))` 🎨
// **Typography:**
// - font-weight: `var(--ui-weight-medium)` 🎨
const TreeItemSelected = "tree-item--selected"

