// Code generated by cssgen. DO NOT EDIT.
//
// Component: Context Panel
// Generated: 2026-02-06 10:18:37

package cssgen

// Context Panel component styles
//
// For the full CSS class registry, see styles.gen.go

// **Layout:**
// - display: `flex`
// - flex-direction: `column`
// - gap: `var(--ui-space-sm)` 🎨
const ModelContext = "model-context"

// **Base:** .model-context
// **Context:** Use with .model-context for proper styling
// **Overrides:** 5 properties (align-items, border-bottom, font-size, justify-content, padding)
//
// **Visual:**
// - border-bottom: `var(--ui-border-sm) solid var(--ui-color-outline)` 🎨
// **Layout:**
// - align-items: `center`
// - display: `flex`
// - justify-content: `space-between`
// - padding: `var(--ui-space-xs) 0` 🎨
// **Typography:**
// - font-size: `var(--ui-type-size-sm)` 🎨
//
// **Interactions:**
// - `:last-child`: Changes border-bottom to `none`
const ModelContextColumn = "model-context__column"

// **Base:** .model-context
// **Context:** Use with .model-context for proper styling
// **Overrides:** 1 properties (font-family)
//
// **Typography:**
// - font-family: `var(--ui-font-code)` 🎨
const ModelContextColumnName = "model-context__column-name"

// **Base:** .model-context
// **Context:** Use with .model-context for proper styling
// **Overrides:** 5 properties (background, border-radius, color, font-size, padding)
//
// **Visual:**
// - background: `var(--ui-color-surface-variant)` 🎨
// - border-radius: `var(--ui-radius-xs)` 🎨
// - color: `var(--ui-color-surface-variant-on)` 🎨
// **Layout:**
// - padding: `1px var(--ui-space-xs)` 🎨
// **Typography:**
// - font-size: `var(--ui-type-size-xs)` 🎨
const ModelContextColumnType = "model-context__column-type"

// **Base:** .model-context
// **Context:** Use with .model-context for proper styling
// **Overrides:** 5 properties (list-style, margin, max-height, overflow-y, padding)
//
// **Layout:**
// - list-style: `none`
// - margin: `0`
// - max-height: `300px`
// - overflow-y: `auto`
// - padding: `0`
const ModelContextColumns = "model-context__columns"

// **Base:** .model-context
// **Context:** Use with .model-context for proper styling
// **Overrides:** 4 properties (color, font-size, font-weight, text-transform)
//
// **Visual:**
// - color: `var(--ui-color-surface-variant-on)` 🎨
// **Typography:**
// - font-size: `var(--ui-type-size-xs)` 🎨
// - font-weight: `var(--ui-weight-semibold)` 🎨
// - text-transform: `uppercase`
const ModelContextLabel = "model-context__label"

// **Base:** .model-context
// **Context:** Use with .model-context for proper styling
// **Overrides:** 7 properties (color, cursor, font-family, font-size, list-style, margin, padding)
//
// **Visual:**
// - color: `inherit`
// **Layout:**
// - cursor: `pointer`
// - list-style: `none`
// - margin: `0`
// - padding: `var(--ui-space-xs) 0` 🎨
// **Typography:**
// - font-family: `var(--ui-font-code)` 🎨
// - font-size: `var(--ui-type-size-sm)` 🎨
//
// **Interactions:**
// - `:hover`: Changes text-decoration to `underline`
const ModelContextList = "model-context__list"

// **Base:** .model-context
// **Context:** Use with .model-context for proper styling
// **Overrides:** 1 properties (gap)
//
// **Layout:**
// - display: `flex`
// - flex-direction: `column`
// - gap: `var(--ui-space-xs)` 🎨
const ModelContextSection = "model-context__section"

// **Base:** .model-context
// **Context:** Use with .model-context for proper styling
// **Overrides:** 1 properties (font-size)
//
// **Typography:**
// - font-size: `var(--ui-type-size-sm)` 🎨
const ModelContextValue = "model-context__value"

// **Base:** .ui-context-panel
// **Context:** Use with .ui-context-panel for proper styling
// **Overrides:** 5 properties (color, font-size, font-weight, margin-bottom, text-transform)
//
// **Visual:**
// - color: `var(--ui-color-surface-variant-on)` 🎨
// **Layout:**
// - margin-bottom: `var(--ui-space-md)` 🎨
// **Typography:**
// - font-size: `var(--ui-type-size-xs)` 🎨
// - font-weight: `var(--ui-weight-semibold)` 🎨
// - text-transform: `uppercase`
const UiContextPanelHeader = "ui-context-panel__header"

