// Code generated by cssgen. DO NOT EDIT.
//
// Component: Log Drawer
// Generated: 2026-02-05 21:28:45

package cssgen

// Log Drawer component styles
//
// For the full CSS class registry, see styles.gen.go

// **Visual:**
// - background: `var(--ui-color-surface-container)` 🎨
// - border-top: `var(--ui-border-sm) solid var(--ui-color-outline)` 🎨
// **Layout:**
// - display: `flex`
// - flex-direction: `column`
// - height: `var(--log-drawer-height)`
const UiLogDrawer = "ui-log-drawer"

// **Base:** .ui-log-drawer
// **Context:** Use with .ui-log-drawer for proper styling
// **Overrides:** 1 properties (height)
//
// **Layout:**
// - height: `32px`
const UiLogDrawerCollapsed = "ui-log-drawer--collapsed"

// **Base:** .ui-log-drawer
// **Context:** Use with .ui-log-drawer for proper styling
// **Overrides:** 5 properties (flex, font-family, font-size, overflow-y, padding)
//
// **Layout:**
// - flex: `1`
// - overflow-y: `auto`
// - padding: `var(--ui-space-sm)` 🎨
// **Typography:**
// - font-family: `var(--ui-font-code)` 🎨
// - font-size: `var(--ui-type-size-sm)` 🎨
const UiLogDrawerContent = "ui-log-drawer__content"

// **Base:** .ui-log-drawer
// **Context:** Use with .ui-log-drawer for proper styling
// **Overrides:** 8 properties (align-items, border-bottom, color, cursor, font-size, font-weight, gap, padding)
//
// **Visual:**
// - border-bottom: `var(--ui-border-sm) solid var(--ui-color-outline)` 🎨
// - color: `var(--ui-color-surface-variant-on)` 🎨
// **Layout:**
// - align-items: `center`
// - cursor: `pointer`
// - display: `flex`
// - gap: `var(--ui-space-md)` 🎨
// - padding: `var(--ui-space-sm) var(--ui-space-md)` 🎨
// **Typography:**
// - font-size: `var(--ui-type-size-sm)` 🎨
// - font-weight: `var(--ui-weight-medium)` 🎨
const UiLogDrawerHeader = "ui-log-drawer__header"

