// Code generated by scripts/gendialect. DO NOT EDIT.
// Source: DuckDB v1.1.3
// Generated: 2026-01-05

package duckdb

// duckDBTypes contains all supported data types for LSP completions.
// Source: SELECT DISTINCT type_name FROM duckdb_types()
var duckDBTypes = []string{
	"JSON", "BIGINT", "BOOL", "BOOLEAN", "BPCHAR",
	"CHAR", "DATE", "DATETIME", "DEC", "DECIMAL",
	"DOUBLE", "FLOAT", "FLOAT4", "FLOAT8", "HUGEINT",
	"INT", "INT1", "INT128", "INT16", "INT2",
	"INT32", "INT4", "INT64", "INT8", "INTEGER",
	"INTEGRAL", "INTERVAL", "LIST", "LOGICAL", "LONG",
	"MAP", "NUMERIC", "NVARCHAR", "OID", "REAL",
	"ROW", "SHORT", "SIGNED", "SMALLINT", "STRING",
	"STRUCT", "TEXT", "TIME", "TIMESTAMP", "TIMESTAMP_MS",
	"TIMESTAMP_NS", "TIMESTAMP_S", "TIMESTAMP_US", "TIMESTAMPTZ", "TIMETZ",
	"TINYINT", "UBIGINT", "UHUGEINT", "UINT128", "UINT16",
	"UINT32", "UINT64", "UINT8", "UINTEGER", "UNION",
	"USMALLINT", "UTINYINT", "VARCHAR",
}
